saucelabs/saucectl

cli/command/new/cmd.go, cli/command/new/templates.go, cli/docker/docker.go
The `new` command generates a sample config that references the new playwright/puppeteer image.
This change was necessary to adhere to the new image naming and versioning that our playwright/puppeteer images now use.
=> Use the new image naming scheme

cli/runner/local.go
Uses the correct port for socat port forwarding.
Previously, a dynamic port was allocated and forward to. That wasn't the port used by saucectl's port bindings however. Furthermore, we don't need to dynamically allocate a port inside the container.
=> Use the correct port for socat

cli/command/new/cmd.go, cli/command/new/templates.go, cli/command/run/cmd.go, cli/config/config.go, cli/docker/docker.go, cli/runner/ci.go
Currently, we only support the sauce labs us-west-1 region (we target this environment by default).
This change will keep up defaulting to us-west-1 for consistency, but allow for other regions to be specified.
The region can be specified via the config and the CLI args.
The user will also receive a sauce region prompt when running the `new` command.
=> Allow region selection

README.md, cli/command/run/cmd.go, cli/config/config.go, cli/docker/docker.go, cli/runner/ci.go
Add ability to pass in environment variables via job configuration or CLI args.
CLI args take precedence over the job configuration.
=> Add ability to pass in environment variables

cli/docker/docker.go, cli/docker/docker_test.go, cli/mocks/docker.go
This change introduces the capability of copying over entire folders (and their files and subfolders). This extends the current support of file patterns.
e.g. if you had a project test folder structure like this:
```
tests
tests/foo.spec.js
tests/subdir/bar.spec.js
```
then specifying the entire folder in the `config.yaml`, would copy over all of its contents to the container like this:
```
files:
- ./tests/
```
=> Folder support

cli/command/run/cmd.go
Prior to this change, there was always a chance of a container left orphaned in the background if some step in the container setup or test execution fails.
This change ensures that a container is cleaned up regardless of what phase it is in.
=> Ensure teardown is run

Makefile, cli/config/config.go
This PR is part of the config variant 2 changes and introduces the notion of `Suites`.
No actual new features have been introduced, nor would anything happen if the user were to specify suites as part of their config at the moment. This change merely adds the capability to parse a config with suites defined.
=> Add suites

.github/workflows/test.yml, .sauce/cypress.yml, .sauce/playwright.yml, .sauce/puppeteer-suites.yml, .sauce/puppeteer.yml, .sauce/testcafe.yml, cli/command/run/cmd.go, cli/config/config.go, cli/runner/runner.go, internal/ci/runner.go, internal/docker/docker.go, internal/docker/docker_test.go, internal/docker/runner.go, tests/e2e/cypress/example.test.js, tests/e2e/playwright/example.test.js, tests/e2e/puppeteer/example.test.js, tests/e2e/testcafe/example.test.js
Introduces rudimentary support for test suites, with backwards compatibility.
If the config has suites specified, they will be used and the capabilities and files on the project level (the root of the config) will be ignored. If no suites are specified, saucectl will continue to work as before.
The test runner will run once per test suite, but stop on the first test suite failure.
The `match` field is currently ignored.
Example config:
```
apiVersion: v1
metadata:
name: Feature XYZ
tags:
- e2e
- release team
- other tag
build: Release $CI_COMMIT_SHORT_SHA
suites:
- name: "my shiny suite"
capabilities:
browserName: "chromium"
files:
- ./tests/example.test.js
- name: "my fiery suite"
capabilities:
browserName: "firefox"
files:
- ./tests/example.test.js
image:
base: …
```
=> Add rudimentary support for suites

internal/ci/ci.go
We may not always want saucectl to think it's inside a container whenver saucectl is run from a CI environment. This pull-request makes an exception for if the platforms is windows or macos; and it makes an exception if an environment variable `SKIP_CI` was passed to it.
This also makes it so we can test our containers using saucectl in CI.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the …
=> feat: Add SKIP_CI parameter to saucectl

.goreleaser.yml
`tar` is not a standard command on Windows hosts, `zip` is much more common.
To avoid requiring installation of a new software to access the binary, archive windows binaries is adviced.
Demo release: https://github.com/FriggaHel/saucectl/releases/tag/v0.13.0-windows-zip
It is assertable that windows binaries are now in `zip` format.
=> Archive export for windows as zip

.sauce/cypress.yml, .sauce/playwright.yml, .sauce/puppeteer.yml, .sauce/puppeteer_parallel.yml, cli/command/run/cmd.go, cli/config/config.go, go.sum, internal/ci/runner.go, internal/ci/runner_test.go, internal/docker/docker.go, internal/docker/docker_test.go
Replace `capabilities` with `settings` in config files for project. But it's still remain backwards compatibility for `suites`.
It would behave like follows:
1. It should use `settings` when only `settings` exists.
2. It should use `capabilities` when only `capabilities` exists.
3. It should use `settings` when `capabilities` and `settings` both exist.
=> Replace capabilities with settings in config files

cmd/saucectl/saucectl.go
Log local time rather than UTC time. It makes more sense for a running-locally cmd.
Example:
```
3:10PM ERR failed to execute new command error=interrupt
```
=> Log local time rather than UTC time

cli/command/new/templates.go, cli/command/run/cmd.go, cli/command/run/cmd_test.go, go.mod
Add args to run by specified suite name. Given suite name, it will directly replace `Project.Suites` with the suite.
Run firefox suite
```
saucectl run --suite firefox
```
Run all suites
```
saucectl run
```
Run non-existed suite
```
saucectl run --suite 233
5:16PM ERR failed to execute run command error="suite name is invalid"
```
Run without args
```
saucectl run --suite
panic: flag needs an argument: --suite
```
=> DEVX-311 add args to run by specified suite name

README.md, cli/command/commands/commands.go, cli/command/configure/cmd.go, cli/command/new/cmd.go, cli/command/new/templates_test.go, cli/command/run/cmd.go, cli/credentials/credentials.go, cli/credentials/credentials_test.go, go.mod, internal/docker/docker.go, internal/testcomposer/testcomposer.go, internal/testcomposer/testcomposer_test.go, internal/yaml/file.go
`saucectl` is able to upload artifacts and results to SauceLabs if there is an authentication token provided.
The only current way to provide it through a couple of environment variable (`SAUCE_USERNAME` / `SAUCE_ACCESS_KEY`).
While it's convenient for a CI environment, this is not optimum for running it locally.
This PR adds support for a local user configuration that will keep `username` and `accessKey` across the different terminals and shells.
It also come with an helper command that allow configure it easily without editing files (`saucectl configure`).
=> feat: store SauceLabs authentication token

cli/command/run/cmd.go
Validate file path before binding to docker when parsing files path from sauce config.
When there is any non-existing file, the output should be
```
1:19AM INF Reading config file config=./.sauce/cypress.yml
1:19AM ERR failed to execute run command error="stat test/e2e/cypress/: no such file or directory"
```
The original issue https://github.com/saucelabs/saucectl/issues/98
=> enhancement: check whether files in sauce config are existed before test

cli/command/run/cmd.go
It meets panic when there's no env setting in config but passing env from cli which caused by allocated map.
=> Fix panic when passing env from cli

cli/command/run/cmd.go, internal/cypress/config.go, internal/cypress/sauce/runner.go, internal/job/starter.go, internal/testcomposer/testcomposer.go, internal/testcomposer/testcomposer_test.go
Starts cypress inside Sauce Labs by calling test-composer with a fire-and-forget request.
Even if the request were to succeed (which it wouldn't right now, since the cloud is not ready), no further action is taken by saucectl.
Polling for job completion and status evaluation will be tackled in a future PR.
The expected output right now is:
```
./saucectl run -c .sauce/cypress.yml --test-env sauce
2:43PM INF Running version unknown-version
2:43PM INF Reading config file config=.sauce/cypress.yml
2:43PM INF Running Cypress in Sauce Labs
2:43PM ERR Caution: Not yet implemented.
2:43PM INF Project uploaded. fileID=bdfc4a1c-05b7-4ebb-a829-0d65f89aa1ac
2:43PM INF Starting job. suite="saucy test"
2:43PM ERR failed to execute run command error="job start failed; unexpected response code:'500', …
```
=> Start cypress job with test-composer

.sauce/cypress.yml, cli/config/config.go, internal/cypress/config.go, internal/cypress/docker/docker.go, internal/docker/docker.go
In some cases, the docker server is not hosted on the same machine, so using mount points does not permit to share files.
As an alternative solution, this PR implement in `saucectl` the ability to copy files into the container.
=> Provide docker copy as an alternative to docker mount path (Cypress Native)

cli/command/run/cmd.go, internal/cypress/sauce/runner.go, internal/job/job.go, internal/job/reader.go, internal/resto/client.go, internal/resto/client_test.go, internal/resto/response.go
Add a job poll after launching a sauce test in the sauce cloud.
The expected result is akin to:
```
./saucectl run -c .sauce/cypress.yml --test-env sauce
11:59AM INF Running version unknown-version
11:59AM INF Reading config file config=.sauce/cypress.yml
11:59AM INF Running Cypress in Sauce Labs
11:59AM ERR Caution: Not yet implemented.
11:59AM INF Project uploaded. fileID=69993be1-c514-4202-aace-32fc9677b0a5
11:59AM INF Starting job. suite="saucy test"
11:59AM INF Job started. jobID=7992eb0f2e4a4863a48401b13f2f1ae6
11:59AM INF Suite passed. suite="saucy test"
```
(disclaimer: since a full e2e is not available, I had re-purposed an already existing job for this)
Worth noting:
No concurrency in place yet (suites are run sequentially) and will be handled in a future PR.
No distinction …
=> Poll for job end

cli/command/new/cmd.go, cli/command/run/cmd.go, cli/config/config.go, internal/cypress/config.go
`saucectl new` command open the configuration file and save it while updating the region.
As the config format has changed for cypress, this command has been broken.
This PR fixes this unexpected behaviour.
=> Cypress native config: Fix saucectl new command

internal/cypress/docker/docker.go, internal/cypress/docker/runner.go
To allow using env variables from a suite we need to pass these variables to a docker container during running cypress in docker mode.
=> add env vars to the cypress in docker

internal/cypress/sauce/runner.go, internal/job/starter.go, internal/testcomposer/testcomposer.go, internal/testcomposer/testcomposer_test.go
To ensure we don't have saucectl trying to access backend in case of restricted framework, this PR implements a check before uploading and trying to run the test package.
Should be merge after backend availability
=> Check for framework availability before trying to start tests

internal/cypress/sauce/runner.go, internal/testcomposer/testcomposer.go
This PR enhances the messaging about errors in suites.
Before:
```
$> saucectl run -c .sauce/staging.yml --test-env sauce --region staging --ccy 2
11:09AM INF Running version unknown-version
11:09AM INF Reading config file config=.sauce/staging.yml
11:09AM INF Running Cypress in Sauce Labs
11:09AM ERR Caution: Not yet implemented.
11:09AM INF Project uploaded. fileID=xxxxxxxx-xxxx-xxxx-xxxx-c81d39fea402
11:09AM INF Launching workers. concurrency=2
11:09AM INF Starting job. suite="Firefox Tests"
11:09AM INF Suites completed: 0 in progress: 2
11:09AM INF Starting job. suite="Chrome Tests"
11:09AM INF Suites completed: 1 in progress: 1
11:09AM INF Suite name: Firefox Tests
11:09AM INF Browser: firefox
11:09AM INF Passed: false
11:09AM WRN Failed to get job asset. suite="Firefox Tests" …
```
=> Enhance messaging when a suite fails

internal/job/job.go, internal/testcomposer/testcomposer.go, internal/testcomposer/testcomposer_test.go
Field mapping between `test-composer` and `saucectl` were not consistent and generating non-errors.
=> Capture TestComposer jobID from API correctly

internal/cypress/sauce/runner.go
No jobId is currently returned when a job has errors.
Console is not printed nor link is provided.
=> Don't return empty job when test failed

.github/workflows/release.yml, .github/workflows/test.yml, .goreleaser.yml
- Update GoReleaser configuration to remove deprecated & removed compatibility from old taps config.
- Check for GoReleaser configuration when creating a PR.
- Updated workflow `on:` field to trigger release only when building new tags not new branches See [here](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags)
=> Update goreleaser config + workflow

.sauce/cypress.yml, .sauce/cypress_cloud.yml, cli/command/run/cmd.go, cli/config/config.go, internal/cypress/config.go, internal/cypress/sauce/runner.go
Add concurrency flag to config. The concurrency setting can now be applied via CLI args or the config itself. CLI arg takes precedence.
=> Add concurrency flag to config

cli/command/run/cmd.go, internal/concurrency/concurrency.go, internal/concurrency/concurrency_test.go, internal/concurrency/reader.go, internal/cypress/sauce/runner.go, internal/resto/client.go
Limit concurrency based on account settings. Users are limited either way on the server side, but this step ensures that we aren't needlessly queuing up the jobs on the server side, while giving the impression to the customer that those are indeed executed (rather than just sitting around in the queue and waiting for their turn).
Users are still able to limit their concurrency below what they have available. If they specify a higher value, they'll be limited to what is available on their account.
=> Limit concurrency based on account settings

internal/cypress/config.go
Prevents internal values of the config from being rendered out. This happened on `saucectl new` when the template was rendered out.
=> Do not render out internal values of the config

cli/command/run/cmd.go
Add cli parameter to allow overriding the configuration value of tunnel-id/tunnel-parent.
=> Add cli parameter to override tunnel-id/parent

.github/workflows/test.yml, .sauce/playwright.yml, Makefile, cli/command/new/cmd.go, cli/command/new/cmd_test.go, cli/command/run/cmd.go, cli/command/run/cmd_test.go, cli/config/config.go, cli/config/config_test.go, go.mod, internal/playwright/config.go, internal/playwright/docker/docker.go, internal/playwright/docker/docker_test.go, internal/playwright/docker/runner.go, internal/playwright/docker/runner_test.go, internal/playwright/sauce/runner.go, internal/region/region_test.go, tests/e2e/playwright/example.test.js
Implement Playwright native configuration.
It ships both implementation for running locally and on Sauce Cloud.
Similar logic to https://github.com/saucelabs/saucectl/pull/158 may be implemented, to ensure consistency of behaviour.
To pass PR `saucectl tests pipeline / playwright (pull_request)`, we must have an image which is based on something else than `jest` (which is WIP).
=> Playwright native configuration

cli/command/run/cmd.go, internal/docker/legacydocker/legacydocker.go, internal/docker/legacydocker/legacydocker_test.go, internal/docker/legacydocker/legacyrunner.go, internal/docker/legacydocker/legacyrunner_test.go
Move legacy docker implementation to avoid collisions.
No logic changes. Simple refactor.
=> Move legacy docker implementation to avoid collisions

cli/command/run/cmd.go, internal/saucecloud/cypress.go, internal/saucecloud/cypress_test.go
Relocate the cypress cloud package to a newly shared `saucecloud` package.
No logic changes. Simple refactor.
=> Relocate cypress cloud package

internal/docker/cypress.go, internal/docker/docker.go, internal/docker/docker_test.go
Remove project specific references from docker. This will allow the docker implementation to be shared across various framework specific runners.
=> Remove project specific references from docker

internal/saucecloud/playwright.go
As playwright is considered to be a browser, we need to enforce this setting for each playwright running in cloud.
=> In playwright force browser to be playwright

internal/saucecloud/cloud.go, internal/saucecloud/cypress.go, internal/saucecloud/playwright.go
Queue up the jobs asynchronously.
This allows us to proceed to the result collection step immediately and therefore display the waiting dots without any delay.
Also included are minor log statement adjustments for a cleaner look overall.
Example output:
```
./saucectl run -c .sauce/cypress_cloud.yml --test-env sauce --ccy 1
15:43:07 INF Running version unknown-version
15:43:07 INF Reading config file config=.sauce/cypress_cloud.yml
15:43:07 INF Running Cypress in Sauce Labs
15:43:07 INF Project archived. bytes=307463
15:43:09 INF Project uploaded. storageId=49527225-e3ae-4bc3-87a9-f7c6c6238baf
15:43:09 INF Launching workers. concurrency=1
15:43:09 INF Starting suite. region=us-west-1 suite="saucy chrome test"
..15:43:11 INF Suite started. suite="saucy chrome test" …
```
=> Dotter delay fix

cli/command/run/cmd.go, internal/docker/container.go, internal/docker/cypress.go, internal/docker/docker.go, internal/docker/docker_test.go, internal/docker/playwright.go
Implement parallelism for docker mode.
Relates to:
- https://github.com/saucelabs/sauce-cypress-runner/pull/101
- https://github.com/saucelabs/sauce-playwright-runner/pull/67
- https://github.com/saucelabs/sauce-testcafe-runner/pull/39
Implements logic for running docker in parallel.
Forces fileTransfer to be `copy` when running in parallel mode to avoid side-effects due to shared folder.
Log console only if tests fails (except if `--show-console-log` is provided).
Remaining to do:
=> Add docker parallelism

internal/docker/container.go, internal/docker/cypress.go, internal/docker/playwright.go, internal/docker/testcafe.go, internal/framework/framework.go, internal/testcomposer/testcomposer.go, internal/testcomposer/testcomposer_test.go
Add a more generic interface for retrieving metadata.
This can then be used by the templator (aka example generator) and image retrieval as well as any other metadata in the future, without the need to further extend the interface.
=> Add a more generic interface for retrieving metadata

internal/framework/framework.go, internal/framework/framework_test.go
Add function for segmenting git release metadata.
=> Add function for segmenting git release metadata

Makefile, cli/command/new/cmd.go, cli/command/new/cmd_test.go, cli/command/new/templates.go, cli/command/new/templates_test.go
Have the 'new' command acquire release information from test-composer.
This means only fully blessed releases that have been configured in test-composer are part of the `saucectl new` process.
=> Have the 'new' command acquire release information from test-composer

cli/command/new/cmd.go, cli/command/new/cmd_test.go
Simply replace region string instead of marshall/unmarshall config file.
More efficient, and allow to keep comments provided in configuration files.
Also, it avoid from missing this update when adding new frameworks.
It is relatively safe to simply rely on `string.Replace()` since we control the input, and this is really not likely that we will have the same field a the same level in Yaml.
=> Update region without marshall/unmarshall

cli/command/new/cmd.go
Pick default runner instead of latest when looking for a new template.
Prior to this change:
```
> saucectl new
Choose a framework: Testcafe
Choose the sauce labs region: us-west-1
13:23:08 INF Downloading template. release=https://github.com/saucelabs/sauce-testcafe-runner/releases/tag/v0.3.1
New project bootstrapped successfully! You can now run:
$ saucectl run
```
`v0.3.1` was picked because it's the latest release.
After this change:
```
> saucectl new
Choose a framework: Testcafe
Choose the sauce labs region: us-west-1
13:24:19 INF Downloading template. release=https://github.com/saucelabs/sauce-testcafe-runner/releases/tag/v0.2.5
New project bootstrapped successfully! You can now run:
$ saucectl run
```
`v0.2.5` is now picked because it's the default release.
=> Pick default runner instead of latest when looking for a new template

internal/docker/container.go, internal/msg/msg.go, internal/saucecloud/cloud.go
Improve status logging by replacing the dotter with a regular interval based log, since the dotter breaks the structured logging output.
Furthermore, simplify the test summary and increase its footprint so it's more of an eyecatcher.
Here's an example for test success:
And one for test failure:
=> Improve status logging

cli/command/configure/cmd.go, cli/command/new/cmd.go, cli/command/new/templates.go, go.mod, go.sum
Switch prompt library to the original version (not the forked out).
Also, add flags to bypass the prompt so that it's automatable. Using stdin on a multiline prompt with the lib we have is not working, hence the flags. I tried other available golang prompt libs and observed similar issues.
=> Add flags to bypass the new command prompt

internal/saucecloud/testcafe.go
Use rootDir for archiving files with testcafe.
While the previous implementation did set the `rootDir` equal to the `projectPath` (if so specified), it failed to use the `rootDir` at the end of the day. So if the fallback wasn't used and the user specified `rootDir` directly, the archiving for sauce cloud would fail.
```
saucectl run --test-env sauce
15:55:39 INF Running version v0.0.0+unknown
15:55:39 INF Reading config file config=.sauce/config.yml
15:55:39 INF Running Testcafe in Sauce Labs
15:55:39 ERR failed to execute run command error="stat : no such file or directory"
```
=> Use rootDir for archiving files with testcafe

internal/docker/cypress.go, internal/saucecloud/cypress.go
Currently, when running cypress run (either docker or cloud), if `rootDir` is defined, cypress project will be added twice at 2 different locations.
Example here:
```
10:22:29 INF Starting container id=2a03ebf5b78d img=saucelabs/stt-cypress-mocha-node:latest suite="saucy test"
10:22:29 INF File copied from=tests/cypress.json suite="saucy test" to=/home/seluser/__project__/
10:22:30 INF File copied from=tests/cypress suite="saucy test" to=/home/seluser/__project__/
10:22:30 INF File copied from=. suite="saucy test" to=/home/seluser/__project__/
```
`cypress.json` will be both in `/home/seluser/__project__/` and `/home/seluser/__project__/tests/`.
This PR remove this duplication.
=> Cypress: Add priority to rootDir over cypress project folder

internal/config/config.go
If the config file is empty or invalid, it should point out there's no test file detected.
```
./saucectl run -c test.json
13:31:12 INF Running version v0.0.0+unknown
13:31:12 INF Reading config file config=test.json
13:31:12 ERR failed to execute run command error="invalid sauce config. You can check config from here https://docs.saucelabs.com/testrunner-toolkit/configuration"
```
=> Fix parsing wrong config issue

internal/archive/tar/tar.go, internal/archive/tar/tar_test.go
With `rootDir` being set to `.`, all files and folders in that folder are getting there `.` remove when archived.
(`.sauceignore` become `sauceignore`, `.sauce` become `sauce`).
This PR fixes this issue.
=> tar: Avoid removal of leading . while archiving

.sauce/puppeteer.yml, cli/command/run/cmd.go, internal/config/config.go, internal/docker/puppeteer.go, internal/puppeteer/config.go
Add support for new puppeteer native config.
Docker mode only.
Corresponding puppeteer image changes: https://github.com/saucelabs/sauce-puppeteer-runner/pull/55
Suggest config layout:
```yaml
apiVersion: v1alpha
kind: puppeteer
sauce:
region: us-west-1
metadata:
name: Testing Puppeteer Support
tags:
- e2e
- release team
- other tag
build: Release $CI_COMMIT_SHORT_SHA
rootDir: tests/e2e/puppeteer
puppeteer:
version: 3.0.4
suites:
- name: "chrome"
testMatch: ["**/example.test.js"]
browser: "chrome"
docker:
image: saucelabs/stt-puppeteer-jest-node:latest
```
=> Add support for new puppeteer native config

internal/docker/container.go, internal/docker/cypress.go, internal/docker/playwright.go, internal/docker/puppeteer.go, internal/docker/testcafe.go
Print out filetransfer mode enforcement only when there's a delta.
Prior to this change, the user would always see this message, even if copy mode was already being used.
=> Print out filetransfer mode enforcement only when there's a delta

cli/command/configure/cmd.go
Updates:
- Exit code to be 1 when credential are invalid
- Message should be red and in an `ERR` line
Result:
```
$> (echo test; sleep 2; echo test) | ./saucectl configure ; echo $?
10:08:09 INF Start Configure Command
Don't have an account? Signup here:
https://bit.ly/saucectl-signup
Already have an account? Get your username and access key here:
https://app.saucelabs.com/user-settings
? SauceLabs username test
? SauceLabs access key test
10:08:11 ERR Credentials provided looks invalid and won't be saved.
10:08:11 ERR failed to execute configure command error="invalid credentials provided"
1
$>
```
=> saucectl configure: Enhance error visibility

cli/command/new/cmd.go, go.mod, internal/credentials/credentials.go
`saucectl new` should raise an error if there is no credentials set.
=> new: Raise error if no credentials set

.sauce/cypress.yml, .sauce/cypress_cloud.yml, internal/archive/tar/tar.go, internal/cypress/config.go, internal/docker/container.go, internal/docker/cypress.go, internal/docker/docker.go, internal/docker/docker_test.go, internal/docker/playwright.go, internal/docker/puppeteer.go, internal/docker/testcafe.go, internal/playwright/config.go, internal/saucecloud/cloud.go, internal/saucecloud/cypress.go, internal/saucecloud/cypress_test.go, internal/saucecloud/playwright.go, internal/saucecloud/testcafe.go, internal/testcafe/config.go
To keep file organisation as user configured it, default rootDir to `.`.
So it solve some issues concerning folder organisation.
=> rootDir defaults to . if empty

cli/command/configure/cmd.go
Use consistent formatting for the 'configure command' prinout.
```shell
> saucectl configure
13:57:23 INF Start Configure Command
Don't have an account? Signup here:
https://bit.ly/saucectl-signup
Already have an account? Get your username and access key here:
https://app.saucelabs.com/user-settings
? SauceLabs username abc
? SauceLabs access key xyz
13:57:24 INF You're all set !
```
```shell
> saucectl configure
Don't have an account? Signup here:
https://bit.ly/saucectl-signup
Already have an account? Get your username and access key here:
https://app.saucelabs.com/user-settings
? SauceLabs username abc
? SauceLabs access key xyz
You're all set!
```
=> Use consistent formatting for the 'configure command' prinout

cli/command/run/cmd.go
Removes the warning ` WRN failed to attach configuration`.
Relates to: https://github.com/saucelabs/saucectl-puppeteer-example/issues/4
=> fix: Set region URL in puppeteer setup steps

internal/cypress/config.go, internal/espresso/config.go, internal/espresso/config_test.go, internal/playwright/config.go, internal/testcafe/config.go, internal/testcafe/config_test.go
Adding platform defaults.
Left out puppeteer, since that one's docker only.
=> Add platform defaults

cli/command/run/cmd.go
Test cases failing in DockerMode won't make `saucectl` exit with `exitCode != 0`
=> fix: exit as failed when dockerMode tests don't pass

cli/command/run/cmd.go
Fixes the suite filtering for espresso (filter function wasn't invoked before). This allows suites to be filtered via the CLI arg `--suite`.
=> Fix suite filter for espresso

go.mod, go.sum, internal/junit/junit.go, internal/junit/junit_test.go, internal/saucecloud/cloud.go
`saucectl` currently fetches and prints a job's `console.log` when a suite fails. Espresso tests do not have a console.log, but they do have a junit.xml that is ripe for parsing.
So for failed espresso suites, fetch and parse the `junit.xml` file and pretty print the test output for the failed tests. Prints out a numbered list of errors:
As well as a summary table:
=> Fetch and print junit.xml for failed espresso suites

internal/appstore/appstore.go, internal/appstore/appstore_test.go, internal/mocks/storage.go, internal/saucecloud/cloud.go, internal/storage/project.go
In order to save time of uploading, check if an artifact has already been uploaded.
Use storage API to check if there is a candidate file having the same hash (assumed to be identical).
=> Check if an artifact has already been uploaded

cli/command/run/cmd.go, cli/version/version.go, go.mod, go.sum, internal/github/github.go, internal/github/github_test.go
Add a warning when a newer version of saucectl has been made available.
Timeout limited to `2s` to prevent having an impact on user tests (silently fails).
```
➭ ./saucectl  run
Running version v0.0.0+unknown
15:22:08 WRN An update of saucectl is available (v0.44.0)
15:22:08 INF Reading config file config=.sauce/config.yml
[...]
➭ 
```
```
➭ ./saucectl  run
Running version v0.43.0
15:26:14 WRN An update of saucectl is available (v0.44.0)
15:26:14 INF Reading config file config=.sauce/config.yml
[...]
➭
```
=> Add warning when a newer version is available

cli/command/run/cmd.go, cli/command/run/espresso.go
Simple refactor to prepare for the CLI Driven Execution (no real functional changes). Cleaned up a few descriptions here and there as well along the way.
The new subcommand will remain hidden until it's officially ready.
This is how the help will look like with these changes:
```
~> saucectl help
Please refer to our examples for how to setup saucectl for your project:
- https://github.com/saucelabs/saucectl-cypress-example
- https://github.com/saucelabs/saucectl-espresso-example
- https://github.com/saucelabs/saucectl-playwright-example
- https://github.com/saucelabs/saucectl-puppeteer-example
- https://github.com/saucelabs/saucectl-testcafe-example
- https://github.com/saucelabs/saucectl-xcuitest-example
Usage:
saucectl [command]
Available Commands:
configure   Configure your Sauce Labs …
```
=> Refactor espresso run command handling

cli/command/run/espresso.go, cli/flags/device.go, cli/flags/emulator.go, internal/espresso/config.go, internal/saucecloud/espresso.go
Extend espresso `run` with additional espresso specific flags.
This is not the final PR, as the presence of a config file is still required and additional work is needed in that area.
=> Extend espresso run with additional espresso specific flags

.github/workflows/test.yml
Add global timeout for pipeline test runs. Avoid unnecessary long runs that result in failure anyway (like https://github.com/saucelabs/saucectl/runs/2778324101).
=> Add global timeout for pipeline test runs

.sauce/cypress.yml, .sauce/espresso.yml, .sauce/playwright.yml, .sauce/puppeteer.yml, .sauce/testcafe.yml, .sauce/xcuitest.yml, internal/config/config.go, internal/config/example_test.go, internal/saucecloud/cypress.go, internal/saucecloud/espresso.go, internal/saucecloud/playwright.go, internal/saucecloud/testcafe.go, internal/saucecloud/xcuitest.go
Remove support for `metadata.name`. Job name == suite name.
=> Remove support for metadata.name

internal/cmd/run/espresso.go, internal/espresso/config.go, internal/saucecloud/espresso.go, internal/saucecloud/espresso_test.go
~~Make `shardIndex` optional~~ Remove `shardIndex` and instead if `numShards` is defined, create sharded jobs with `shardIndex` automatically set.
The auto sharding will happen across all devices and emulators defined for a suite. e.g. if `numShards` is 2 and there are 2 devices (say, d1 and d2) and 2 emulators (say, e1 and e2) defined, 8 jobs will be created:
d1 (shard 1 of 2)
d1 (shard 2 of 2)
d2 (shard 1 of 2)
d2 (shard 2 of 2)
e1 (shard 1 of 2)
e1 (shard 2 of 2)
e2 (shard 1 of 2)
e2 (shard 2 of 2)
Not totally sure this is the desired behaviour though.
=> [DEVX-1015] Auto sharding for espresso

internal/cmd/run/espresso.go, internal/cmd/run/run.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/espresso/config.go, internal/espresso/config_test.go, internal/testcafe/config.go, internal/xcuitest/config.go, internal/xcuitest/config_test.go
Make the config entirely optional by allowing the user to specify an empty config path `-c ""`. Before this change, a config, albeit a very empty one, was still required, even when using the "cli driven" approach.
At the moment, this is only available for `espresso`, `testcafe` and `xcuitest`. The docs for this have not been updated, because the entire "cli driven" approach is still a WIP.
=> [DEVX-1052] Allow the user to skip the config entirely

internal/saucecloud/espresso.go, internal/saucecloud/espresso_test.go
Fix jobs count calculation when using sharding. Without the fix, the number of shards is multiplied with the total jobs count on each iteration (issue manifests itself when more than one suite is used and at least one of them uses sharding).
=> [DEVX-1061] Fix jobs count calculation when using sharding

internal/cmd/ini/cypress.go
Add a default pattern for `saucectl init` for Cypress.
=> fix: saucectl init: Define default pattern for Cypress

internal/cmd/run/espresso.go, internal/cmd/run/puppeteer.go, internal/cmd/run/run.go, internal/config/config.go, internal/espresso/config.go, internal/flags/binder.go, internal/puppeteer/config.go
Add viper config/flag binding to espresso.
Due to the fact that you cannot bind flags with the same name multiple times (e.g. `--name` has the same semantic use in saucectl, but used more than once for different subcommands) as a rebinding overwrites the previous one, I had to move the early-binding (command creation time) to a late-binding (command execution time).
The alternative would have been to use multiple viper instances, but that proved to be more brittle and would have required more maintenance going forward.
=> [DEVX-1070] Use espresso with viper

internal/cypress/config.go, internal/cypress/config_test.go, internal/cypress/native.go, internal/cypress/native_test.go
Resolves https://github.com/saucelabs/saucectl/issues/377
Instead of checking presence of `cypress` folder close to `cypress.json`, check using content of that file.
Allow for non-native configuration of `cypress`.
With config containing `"integrationFolder": "e2e/integration"`:
Previously:
```
{16:31}~/Projects/saucectl-cypress-example(master ✗) ➭ saucectl run
Running version 0.55.1
16:31:51 ERR failed to execute run command error="unable to locate the cypress folder in ."
{16:31}~/Projects/saucectl-cypress-example(master ✗) ➭ 
```
Now it's passing !
=> [DEVX-1088] Check cypress following cypress.json file

internal/cmd/ini/cmd.go, internal/cmd/ini/initializer.go, internal/cmd/ini/initializer_test.go
Enhances user experiences when having connection related issues during `saucectl init`.
When backend is unreachable:
When connection lost after region selection:
For Android virtual device list, add an hard-coded list, to avoid disrupting the UX due to low connectivity / slow connection.
Defaults to 1 when concurrency is unreachable (already present, mainly enhance the message).
=> [DEVX-1113] init: Make errors more user-friendly

.sauce/xcuitest.yml, api/v1alpha/framework/xcuitest.schema.json, api/v1alpha/generated/saucectl.schema.json, internal/cmd/run/espresso.go, internal/cmd/run/xcuitest.go, internal/job/starter.go, internal/saucecloud/xcuitest.go, internal/xcuitest/config.go
Currently it's only possible to provide a lists of tests that should be run in an XCUITests (`tests_to_run` on the RDC API). There is now support for specifying a list of tests that should be ignored (`tests_to_skip`).
The usage in the config file is aligned with the existing names `class` and `notClass` (which is already available for Espresso)
=> [MOBA-5500] Allow specifying tests to skip for XCUITest

internal/cypress/config.go, internal/docker/container.go, internal/docker/docker.go, internal/docker/docker_test.go
As reported by https://github.com/saucelabs/saucectl/issues/280, there is a small discrepancy between Docker and Sauce regarding environment vars.
In both cases, env variables are being read from `sauce-runner.json` by the runner and set before invoking Cypress process (or any other framework).
In addition to that, when running in docker move, those variables are being injected before the invocation of the runner.
Summary:
|  | CYPRESS_VAR1 | VAR2 |
| --- | --- | --- |
| Cypress in Docker | Visible as VAR1 | Visible as VAR2 | 
| Cypress in Sauce | Invisible | Visible as VAR2 | 
To avoid that discrepancy, removing the docker-specific implementation seems better.
It will also require an update of docs, stating that variables are directly set in Cypres, and does not require any `CYPRESS_` …
=> [DEVX-1133] Remove specific docker env injection

internal/cmd/run/espresso.go, internal/cmd/run/run.go, internal/cmd/run/xcuitest.go, internal/flags/device.go, internal/flags/emulator.go, internal/flags/simulator.go, internal/msg/msg.go
Improve the UX of the CLI Driven approach by making flag usage more clear. And including examples as part of the help printout.
This PR only covers xcuitest and espresso, as the two most prominent frameworks where the CLI Driven approach is used.
```
~> saucectl run espresso -h
Unlike 'saucectl run', this command allows you to bypass the config file partially or entirely by configuring an adhoc suite (--name) via flags.
Usage:
saucectl run espresso [flags]
Examples:
saucectl run espresso -c "" --name "My Suite" --app app.apk --testApp testApp.apk --otherApps=a.apk,b.apk --device name="Google Pixel.*",platformVersion=14.0,carrierConnectivity=false,deviceType=PHONE,private=false --emulator name="Android Emulator",platformVersion=8.0
Flags:
--app string                         Specifies the …
```
=> [DEVX-1188] Flag clarity

internal/cmd/run/cypress.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/testcafe.go, internal/config/config.go, internal/config/config_test.go, internal/msg/msg.go
Adding the test framework to `npm.packages` is not just redundant since the framework version is pre-installed and defined in the `{{framework}}.version` property in the configuration, it can also cause errors at execution time (e.g. multiple incompatible versions of the test library).
Before execution, remove conflicting framework packages from the list of npm packages to install and print a warning.
Fixes #403
=> [DEVX-1152] Filter out and warn if framework packages are defined in config.yml

.goreleaser.yml, go.mod, go.sum, internal/ci/ci.go, internal/cmd/configure/cmd.go, internal/cmd/ini/cmd.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/docker/container.go, internal/docker/cypress.go, internal/report/captor/captor.go, internal/report/report.go, internal/saucecloud/cloud.go, internal/segment/segment.go, internal/setup/segment.go, internal/usage/tracker.go
Add usage tracking.
This tracks usage across the following commands:
- saucectl init
- saucectl configure
- saucectl run (incl. the framework specific subcommands)
=> [DEVX-1180] Add usage tracking

internal/segment/segment.go
The way our segment sources/destinations are setup, it seems to be rather difficult to extract the `extra` info out of a context, unless it's part of the default fields, like OS.
Hence moving the CI field outside the context and into properties.
=> Capture CI info as part of properties

internal/usage/tracker.go
Prior to this change, we collected the nested object of NPM packages + versions.
Not all downstream tools support "complex" objects like that, making it harder to analyze.
Also, we don't really care about the versions. Thus no reason to collect.
This change simplifies the object into an array.
=> Collect only npm package names

internal/docker/container.go, internal/report/captor/captor.go, internal/report/report.go, internal/report/table/table.go, internal/report/table/table_test.go, internal/saucecloud/cloud.go
Only calculate test duration from the start to the end instead of only adding duration.
Given 2 suites and 2ccy.
Docker:
```
Name                                Duration    Status    Browser                 Platform
───────────────────────────────────────────────────────────────────────────────────────────────────
✔    Chrome using global mode setting         50s    passed    chrome 92.0.4515.159    Docker
✔    Firefox in sauce                         51s    passed    firefox 91.0.2          Docker
───────────────────────────────────────────────────────────────────────────────────────────────────
✔    All tests have passed                    51s
```
Sauce:
```
Name                                Duration    Status    Browser       Platform …
```
=> [DEVX-1218] Fix wrong test total duration

api/v1alpha/framework/cypress.schema.json, api/v1alpha/generated/saucectl.schema.json, go.mod, go.sum, internal/cmd/run/cypress.go, internal/cypress/config.go, internal/cypress/config_test.go, internal/cypress/native.go, internal/cypress/native_test.go
Shard tests automatically by spec, if desired. This will launch as many jobs as there are spec files.
**shard by spec:**
```
Name                                     Duration    Status    Browser      Platform
───────────────────────────────────────────────────────────────────────────────────────────────
✔    all tests - examples/actions.spec.js          47s    passed    chrome 94    Windows 10
✔    all tests - examples/actions3.spec.js         47s    passed    chrome 94    Windows 10
✔    all tests - examples/actions2.spec.js         47s    passed    chrome 94    Windows 10
───────────────────────────────────────────────────────────────────────────────────────────────
✔    All tests have passed                         48s
```
**no sharding:**
```
Name …
```
=> Cypress Test Sharding

internal/cmd/configure/cmd.go, internal/cmd/ini/cmd.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/segment/segment.go
Introduce a flag to disable collecting segment metrics.
```
saucectl run --disable-usage-metrics
```
=> [DEVX-1347] Add a flag to disable collecting segment metrics

internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/docker/container.go, internal/download/artifact.go, internal/download/artifact_test.go, internal/job/job.go, internal/junit/reporter_test.go, internal/notification/slack/slack.go, internal/report/report.go, internal/report/table/table.go, internal/report/table/table_test.go, internal/saucecloud/cloud.go, internal/saucecloud/cypress_test.go, internal/saucecloud/xcuitest_test.go
Add ability to `saucectl run` without waiting for the rest results.
Launch failures will still be caught and awaited.
Regular, sync way:
```
saucectl run
[...]
15:49:40 INF Starting suite. region=us-west-1 suite="saucy barista - test size"
15:49:40 INF Starting suite. region=us-west-1 suite="saucy barista - combined"
15:49:40 INF Starting suite. region=us-west-1 suite="saucy barista - package"
15:49:50 INF Suites in progress: 3
15:50:00 INF Suites in progress: 3
15:50:08 INF Suite started. deviceId= deviceName="Android GoogleApi Emulator" platform=Android platformVersion=11.0 suite="saucy barista - test size" url=https://app.saucelabs.com/tests/bb9518974a474e95b3a38e0244fbcc8e
15:50:10 INF Suite started. deviceId= deviceName="Android GoogleApi Emulator" platform=Android …
```
=> [DEVX-1362] Add ability to launch tests asynchronously

internal/saucecloud/cloud.go
Add clarity (root error) when framework version check is failing.
Before:
```
{15:19}~/Projects/saucectl(main ✗) ➭ saucectl run -c .sauce/cypress.yml --select-suite "saucy test in sauce" --test-env-silent
Running version 0.76.0
15:20:00 INF Running Cypress in Sauce Labs
15:20:02 ERR failed to execute run command error="unable to check framework version availability"
{15:20}~/Projects/saucectl(main ✗) ➭
```
After:
```
{15:20}~/Projects/saucectl(main ✗) ➭ ./saucectl run -c .sauce/cypress.yml --select-suite "saucy test in sauce" --test-env-silent
15:20:11 WRN A new version of saucectl is available (v0.76.0)
15:20:11 INF Running Cypress in Sauce Labs
15:20:13 ERR failed to execute run command error="unable to check framework version availability: unexpected …
```
=> fix: Add error when check version availability is failing

internal/saucecloud/cloud.go
Before:
```
08:21:18 INF Starting suite. region=staging suite="Webkit in sauce"
08:21:28 INF Suites in progress: 1
Name                              Duration    Status    Browser    Attempts
────────────────────────────────────────────────────────────────────────────────────
✖    Webkit in sauce                        11s              webkit            1
────────────────────────────────────────────────────────────────────────────────────
*    All tests have launched                11s
```
After:
```
08:48:51 INF Starting suite. region=staging suite="Webkit in sauce"
08:49:01 INF Suites in progress: 1
08:49:02 ERR Failed to start suite. error="job start failed; unexpected response code:'500', msg:'unexpected status code from ondemand: 500 details: {\"status\": 13, \"sessionId\": …
```
=> [DEVX-1404] Report failed job starts correctly

internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/saucecloud/cloud.go
Introduces a `--fail-fast` parameter.
It skips the non-started suites from being started when one of the previous suites have failed.
=> [DEVX-359] Skip tests after failure

.github/workflows/test.yml, cmd/saucectl/saucectl.go, internal/cmd/doctor/cmd.go, internal/docker/docker.go, internal/doctor/doctor.go
Automate docker integration tests, particularly for windows.
Introduce a new command `doctor` (inspired by `flutter doctor`) that performs a list of checks against saucectl's dependencies. The main concern was/is docker, but can be later extended to check Sauce Labs connectivity, user credentials etc.
```
Run ./saucectl.exe doctor
[•] Docker
[✔] Connection
[✔] Pull Images
[✔] Launch Containers
```
=> Automate Docker Integration Tests

.github/workflows/test.yml, CONTRIBUTING.md, Makefile, internal/docker/container.go, internal/docker/container_test.go, internal/notification/slack/slack_test.go, internal/saucecloud/cloud.go, internal/saucecloud/xcuitest.go
`golint` has been deprecated. Replacing its usage with `go vet`. Though `go vet` is technically not a linter, it may be exactly what we need and nothing more.
=> Replace golint

api/v1alpha/generated/saucectl.schema.json, api/v1alpha/subschema/artifacts.schema.json, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/download/artifact.go
Add a `cleanupPrevious` field in config and saucectl will cleanup previous downloaded artifacts.
=> [DEVX-1440] Add cleanup method for artifacts 

api/v1alpha/framework/cypress.schema.json, api/v1alpha/generated/saucectl.schema.json, internal/cmd/run/cypress.go, internal/cypress/config.go
Allow Cypress to be run in headless mode
(Supported by runners carrying Cypress 8.3.0+)
Relates to https://github.com/saucelabs/saucectl/issues/476
=> [DEVX-1445] Add support for headless on Cypress

README.md
Improve clarity of how to use saucectl by providing a reference to the available flags in the readme.
=> Add flag docs reference

internal/msg/msg.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go
Windows has some contraints on path length.
This PR brings the check before archiving, preventing future failure in VMs.
=> [DEVX-1546] Check for path length before archiving

internal/xcuitest/config.go
Fixes #497 
Feature parity with espresso. Allows variable expansion for the app/testApp fields.
```
xcuitest:
app: $APP
testApp: $TEST_APP
```
=> [DEVX-1569] Expand xcuitest app/testapp variables

api/v1alpha/generated/saucectl.schema.json, api/v1alpha/subschema/reporters.schema.json
Fix the reporter schema. The current properties within the reporter schema actually belong to the junit reporter underneath, which was missing. Relocate the properties and add the junit reporter (see [docs](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/espresso/#reporters)).
=> Fix reporter schema

.sauce/cypress.yml, .sauce/espresso.yml, .sauce/playwright.yml, .sauce/testcafe.yml, .sauce/xcuitest.yml, internal/config/config.go
#524 introduced a new decoding hook, but inadvertently also replaced default decoders that were set by viper itself.
Special values, like `duration`, were handled by those defaults and consequently broke (like our timeout setting).
=> [DEVX-1692] Fix missing default decoders

internal/framework/search.go, internal/framework/search_test.go
It's difficult to diagnose problems during run execution when framework errors are completely generic
Solves #533
None
=> Append misc error strings with actual error messages

internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/cypress/config.go, internal/framework/framework.go, internal/playwright/config.go, internal/puppeteer/replay/config.go, internal/rdc/client.go, internal/rdc/client_test.go, internal/region/region.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/cypress.go, internal/saucecloud/playwright.go, internal/saucecloud/replay.go, internal/saucecloud/testcafe.go, internal/saucecloud/xcuitest_test.go, internal/slice/slice.go, internal/slice/slice_test.go, internal/testcafe/config.go, internal/testcomposer/testcomposer.go, internal/webdriver/webdriver.go, internal/webdriver/webdriver_test.go
Optimize the job start route by skipping test-composer and calling the appropriate services directly.
I kept the changes for this PR as minimal as possible by moving some of the logic from test-composer to saucectl.
Certain places are in need of some TLC and refactor, but those will follow via separate PRs.
=> [DEVX-1725] Job Start Route Optimization

internal/sauceignore/matcher.go
Puppeteer replay doesn't rely on the sauceignore file, since project folders are never packaged up anyway, only the recordings are (kinda like espresso/xcuitest, where only the app/testApp files are uploaded).
The current implementation issues a warning that a sauceignore file is missing, despite explicitly omitting it.
=> [DEVX-1682] Don't log warnings when sauceignore is intentionally omitted

internal/saucecloud/cloud.go
Running in async mode caused the process to have a non-zero exit code. Non-zero exit code should be reserved for errors and actual failed results.
Fixes #554 
I'm not totally sure this is the correct logic. Should timed out jobs be considered non-passing and force a non-zero exit code?
=> Ignore in progress jobs when computing pass/fail for results

api/v1alpha/generated/saucectl.schema.json, api/v1alpha/subschema/npm.schema.json, internal/cmd/run/cypress.go, internal/cmd/run/playwright.go, internal/cmd/run/testcafe.go, internal/config/config.go, internal/node/package.go, internal/saucecloud/cloud.go, internal/sauceignore/matcher.go, internal/sauceignore/matcher_test.go
Allow the user to specify local npm dependencies that ought to be included in the payload. The dependencies must already be present in the `node_modules` directory. The user only needs to specify the "main" dependencies that are required to run their tests. `saucectl` will automatically determine all of the transitive dependencies.
=> Selective Node Module Inclusion

internal/archive/zip/zip.go, internal/archive/zip/zip_test.go, internal/msg/msg.go, internal/saucecloud/cloud.go, internal/saucecloud/xcuitest.go
Print a warning if the project archive has more than 32768 files. The number of files is arbitrary, but corresponds to about 30s of additional test setup time (15s download, 15s extraction).
```🍖 ../saucectl/saucectl run --select-suite "Chrome using global mode setting"
11:10:57 WRN A new version of saucectl is available (v0.100.0)
11:10:57 INF Running Cypress in Sauce Labs
(.
#.
#.
.####################
#####////////*******/######
.##///////*****************###/
,###////*********************###
####//***********************####
###/************************###
######********************###. ##
(########################  ##     ##
,######(#*         ##*   (##
/############*          #####
(########(  #########(    ###
.#######,    */  ############
,########## …
```
=> [DEVX-1761] Warn if project archive is unusually large

internal/segment/segment.go, internal/usage/tracker.go
Mute segment logs. At least a bit.
1. Redirect logs to our own logger, so that they follow our format.
2. Reduce all log levels to debug, since they are 99% irrelevant to the user.
Also include an unrelated change to the above: Capture list of npm dependencies.
=> Mute Segment Logs

internal/archive/zip/zip.go
When archiving the project, we read files fully into memory before writing to the zip archive. This results in linear memory usage in the worst case and might result in OOM errors in some situations where there are very large files to archive.
Buffering the read improves the worst case behaviour to be closer to constant memory usage.
=> Use a buffered reader when reading files to add to zip archive

internal/framework/framework.go, internal/framework/framework_test.go, internal/framework/search.go, internal/framework/search_test.go, internal/msg/msg.go, internal/saucecloud/cypress.go, internal/saucecloud/cypress_test.go, internal/saucecloud/playwright.go, internal/saucecloud/replay.go, internal/saucecloud/testcafe.go
Ensure that only supported platforms can be run. Previously, an edge case existed when targeting a platform that is _generally_ supported for a specific framework but may be unavailable for certain framework versions.
This change introduces a check that is performed on a suite level to verify the availability.
It's slightly less lenient when it comes to platform naming. For example, "macos 11.00" vs "mac 11" vs "macos 11" are not treated as aliases, meaning that only one of them (i.e. "macos 11.00") is accepted. This may break previous customer setups that used one of those aliases before.
=> Ensure that only supported platforms can be run

internal/node/package.go, internal/saucecloud/cloud.go, internal/sauceignore/matcher.go, internal/sauceignore/matcher_test.go
Scoped npm dependencies are correctly resolved, but inaccurate gitignore/sauceignore rules caused them to be excluded during archiving.
=> Fix npm dependency inclusion rules

internal/fpath/file.go
It should get the relative path and then use `filepath.ToSlash()` to replace the separator in relative path. 
Before, comparing
```
pattern: "recordings/myfiles"
relSlashes: "recordings\myfiles"
```
After, comparing
```
pattern: "recordings/myfiles"
relSlashes: "recordings/myfiles"
```
=> [DEVX-1829] Fix path match issue for windows

internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/cypress.go, internal/saucecloud/cypress_test.go, internal/saucecloud/espresso.go, internal/saucecloud/playwright.go, internal/saucecloud/replay.go, internal/saucecloud/testcafe.go, internal/saucecloud/xcuitest.go
Treat node_modules as a separate payload.
This improves cache hits, which in turn improves execution time for projects where code changes more often than dependencies do.
=> Treat node_modules as a separate payload

internal/cmd/run/run.go
Increase timeout for the RDC client. While a larger timeout has no added benefits for starting tests (RDC job creation is asynchronous from actual device assignment), it is for downloading assets.
=> Increase RDC timeout

internal/cmd/run/run.go
Increase RDC timeout to accommodate large asset downloads.
=> Increase RDC timeout to accommodate large asset downloads

internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go
If `node_modules` is empty while the dependencies are required in the config, it will upload an empty dependencies folder which causes the failure. This PR is to fix it.
=> [DEVX-1842] Fix dependencies uploading with empty node_modules folder

.golangci.yml, internal/apps/apps.go, internal/framework/search.go, internal/framework/search_test.go, internal/saucecloud/cloud.go
To maintain our level of code hygiene. `golint` (deprecated) had more styling rules, which carried over to `revive`.
=> Enable additional linter rules

cmd/saucectl/saucectl.go, internal/cmd/cmd.go, internal/cmd/configure/cmd.go, internal/cmd/ini/cmd.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/replay.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/cmd/storage/download.go, internal/cmd/storage/list.go, internal/cmd/storage/upload.go, internal/notification/slack/slack.go, internal/segment/segment.go
Move the usage tracking flag & instantiation to a global level, since the tracker is used across all commands (or at least, it can be used that way).
Also removed the obsolete usage tracking of slack events. Aside from being obsolete, the usage tracker was never meant to track individual events or features within saucectl. Its purpose is to track command usage (things that you can't necessarily see on the server side).
=> Global Usage Tracking Flag

internal/cypress/grep/grep.go
Turns out allowing both empty titles **and** empty tags was too permissive and effectively does almost no filtering.
cypress-grep explicitly matches empty titles so just mimic that specific behaviour. If we want to account for parsing bugs we might want to add some kind of error state when parsing code to detect this specific case.
=> Only permit empty titles, match strict on tags

internal/apitesting/async_test.go, internal/apitesting/client.go, internal/apitesting/client_test.go
The current way `saucectl` is providing tunnel name to API Testing is incorrect.
It needs to be `tunnelOwner:tunnelName` instead of `tunnelName:tunnelOwner`.
Also, when no owner is specified (meaning current user), `username:tunnelName` must be provided.
=> Fix: Tunnel in API Testing

internal/saucecloud/cloud.go
Retrying jobs when _concurrency_ is lower than the number of queued up jobs would cause a jam/deadlock since the channel is full. With this change, jobs will be re-queued asynchronously.
=> Re-queue jobs asynchronously

api/saucectl.schema.json, api/v1alpha/framework/apitest.schema.json, internal/apitest/config.go, internal/apitest/runner.go, internal/apitest/runner_test.go, internal/apitesting/client.go, internal/apitesting/client_test.go, internal/cmd/run/apitest.go, internal/msg/errormsg.go
To enhance usability and easiness of configuration, API Testing will be configure through `ProjectName` instead of `HookID`.
=> API-Testing: Rely on ProjectName instead of HookID

internal/docker/docker.go
Fix typo that causes premature removal of the test container (`saucectl doctor`).
=> Fix docker doctor

.github/workflows/docker-release.yml
Simplify docker smoke test job (which was also failing for [some bizarre reason](https://github.com/saucelabs/saucectl/actions/runs/4088484717/jobs/7050270051)).
=> Simplify docker smoke test

internal/cmd/run/run.go
Remove the deprecated flag `tunnel-parent`. Usage stats indicate that this flag is not used anymore (unlike `tunnel-id`).
The config level setting will remain.
=> Remove deprecated flag tunnel-parent

internal/appstore/appstore.go, internal/appstore/appstore_test.go, internal/saucecloud/cloud.go, internal/saucecloud/cypress_test.go, internal/saucecloud/espresso_test.go, internal/saucecloud/xcuitest_test.go, internal/storage/storage.go
Utilize the previously introduced `storage.UploadStream` method to upload project files (before it was only used by the `saucectl storage` command) and remove deprecated methods.
This change greatly reduces the memory footprint during project uploads.
Some stats with our espresso-example repo before this change:
And after:
=> Reduce memory footprint during uploads

internal/cmd/run/playwright.go, internal/playwright/config.go, internal/playwright/config_test.go
Remove deprecated playwright flags. Confirmed not in use (and not supported by any of our active runners).
=> Remove deprecated playwright flags

internal/cmd/run/run.go, internal/http/imagerunner.go
This is the first PR in a series of PRs to move all our http client implementations of various services (testcomposer, resto & co.) into the `http` package.
This addresses the somewhat organic growth of our package scoped responsibilities and to easier maintain the separation of interfaces and their implementations. In short, less 🍝 and more ✨ packages.
=> Refactor imagerunner

internal/imagerunner/imagerunner.go, internal/saucecloud/imagerunner.go
The API currently requires `user` and `token` to be set if their parent field `auth` is also defined.
Credentials are optional though. Change the field to a pointer so that it's properly omitted during serialization when nil.
=> Fix: Allow empty image credentials

internal/saucecloud/cloud_test.go
Fix the flaky signal test by polling for results, since interrupt signal handling is asynchronous.
Nice side effect: These changes will speed up the test run, as there's no need to wait an entire second for the results.
=> Fix flaky signal test

internal/cmd/artifacts/cmd.go, internal/cmd/artifacts/download.go, internal/cmd/artifacts/list.go, internal/cmd/artifacts/upload.go, internal/saucecloud/artifactservice.go
- remove implementation details (http clients) from ArtifactService
- actually fix `saucectl artifacts upload`, as it wasn't working at all
```
❯ saucectl artifacts upload 4dd90880b3d34923978b2cfb742f2057 demo.gif
Error: failed to upload file: Put "/v1/testcomposer/jobs/4dd90880b3d34923978b2cfb742f2057/assets": unsupported protocol scheme ""
```
- improve usage description
Before:
```
❯ saucectl artifacts upload -h
Uploads an artifacts for the job. Real Device job is not supported.
Usage:
saucectl artifacts upload [flags]
```
^^ What am I supposed to do? No args?
After:
```
❯ saucectl artifacts upload -h
Uploads an artifacts for the job. Real Device job is not supported.
Usage:
saucectl artifacts upload <jobID> <filename> [flags]
```
Clearer now.
=> Refactor Artifacts

internal/cmd/ini/initializer.go, internal/cmd/jobs/cmd.go, internal/cmd/run/run.go, internal/cmd/storage/cmd.go, internal/http/apitester.go, internal/http/appstore.go, internal/http/github.go, internal/http/imagerunner.go, internal/http/insightsservice.go, internal/http/rdcservice.go, internal/http/request.go, internal/http/request_test.go, internal/http/resto.go, internal/http/testcomposer.go, internal/http/userservice.go, internal/http/webdriver.go, internal/requesth/request.go, internal/requesth/request_test.go
Now that the majority of HTTP dependencies have been consolidated, it's time to clean up the imports ✨ 
The package `requesth` becomes obsolete as well, since all calls to it originate from the `http` package, which is where it belongs to.
=> HTTP Cleanup

go.mod, go.sum, internal/http/rdcservice.go, internal/http/rdcservice_test.go, internal/http/resto.go, internal/http/resto_test.go
The unfortunate default behavior of the `retryablehttp` client hides details/errors of the last unsuccessful attempt:
```go
if err == nil {
return nil, fmt.Errorf("%s %s giving up after %d attempt(s)",
req.Method, req.URL, attempt)
}
```
This is usually the case if the server actually responded, but with an unexpected status code. We already have code in place that handles various responses, which could not be utilized due to `retryablehttp` throwing its own error.
This PR ensures that original errors are passed through.
PS: The jury is still out on whether or not to keep use of the `retryablehttp` client.
=> Fix: Propagate last error after exhausting all retry attempts

internal/imagerunner/imagerunner.go, internal/report/table/table.go
Finalize the Imagerunner states. `Terminated` is likely the only observable difference, as it is a final state. Before, we'd have continued to poll for the status, even if the container was already `Terminated`.
=> Finalize Imagerunner states

internal/http/appstore.go, internal/http/appstore_test.go
Propagate the size field back from the server response when uploading to app storage.
```sh
❯ saucectl storage upload somefile.zip -o json
{"id":"REDACTED","name":"somefile.zip","size":729,"uploaded":"2023-02-22T15:08:45-08:00"}
```
Prior to this change, the `size` was reported as 0. This only affected app storage uploads when the output format was set to `json`.
=> Report the correct payload size when uploading app files

internal/cmd/configure/cmd.go, internal/cmd/ini/cmd.go, internal/cmd/ini/initializer.go, internal/cmd/ini/initializer_test.go, internal/cmd/run/run.go, internal/credentials/credentials.go, internal/credentials/credentials_test.go, internal/http/imagerunner.go, internal/http/insightsservice.go, internal/http/insightsservice_test.go, internal/http/testcomposer.go, internal/http/testcomposer_test.go, internal/http/userservice.go, internal/http/webdriver.go, internal/iam/auth.go
Minor refactor that separates out the definition of `credentials` by moving it to the `iam` package, which is where it likely belongs.
Implementation details for the retrieval of stored credentials (env + filesystem) will remain in the `credentials` package. Creating a full blown "CredentialsProvider" felt a bit over-engineered to me compared the convenience that the `credentials` package right now provides.
=> Refactor iam and credentials

.github/workflows/release.yml, .goreleaser.yml
- Make `goreleaser` avoid replacing `pre-release` setting.
- Use `--clean` instead of `--rm-dist` (deprecated)
=> fix: Don't remove pre-release setting

internal/http/imagerunner.go, internal/http/imagerunner_test.go, internal/imagerunner/imagerunner.go, internal/saucecloud/imagerunner.go
Implement artifact downloads for jobs triggered by `ImageRunner` mode.
Potential issues:
- If payload is huge, it may take a long time to download and consume a lot of RAM.
=> ImageRunner: Add Artifact download support

.github/workflows/release.yml, .goreleaser.yml
=> Fix node release

internal/cmd/ini/cmd.go, internal/cmd/ini/common.go, internal/cmd/ini/common_test.go, internal/cmd/ini/imagerunner.go, internal/cmd/ini/initializer.go, internal/cmd/ini/initializer_test.go, internal/msg/errormsg.go
Add init for ImageRunner.
Only support:
- Name
- Artifact downloads
Ouput:
```
➭ saucectl init
11:45:51 INF Start Init Command
? Select region: us-west-1
? Select framework: imagerunner
? Docker Image to use: ubuntu:latest
? Download artifacts: always
The following files have been created:
.sauce/config.yml
Before running your tests, you need to set the following environment variables:
- DOCKER_USERNAME
- DOCKER_PASSWORD
➭
```
=> Add init for ImageRunner mode

internal/cmd/artifacts/download.go, internal/cmd/artifacts/list.go, internal/cmd/artifacts/upload.go, internal/cmd/imagerunner/artifacts.go, internal/cmd/imagerunner/logs.go, internal/cmd/ini/cmd.go, internal/cmd/run/run.go, internal/http/apitester.go, internal/http/appstore.go, internal/http/client.go, internal/http/github.go, internal/http/insightsservice.go, internal/http/proxy.go, internal/http/testcomposer.go, internal/http/userservice.go, internal/http/webdriver.go
This PR adds support for HTTP_PROXY (including proxies with authentication).
Also checks `HTTP_PROXY` right at startup to ensure sanity
=> Add support for HTTP_PROXY

.github/workflows/pull-request-linter.yml, .github/workflows/test.yml
GitHub doesn't have _labeling requirements_ as a feature in their "branch merge protection" settings. Setting labels is easily forgotten (I've done it many times) and our release note generator relies on them.
The label check will run when a PR is created and whenever a label is added or removed from the PR.
=> Ensure PRs are labeled

internal/cmd/artifacts/download.go, internal/cmd/imagerunner/artifacts.go, internal/cmd/imagerunner/logs.go
- Updates usage message for `saucectl imagerunner artifacts download -h` to display expected positional args.
- Fix panic() when `saucectl imagerunner logs` does not provides a `runID`.
=> fix: ImageRunner errors management

internal/saucecloud/retry/junitretrier.go, internal/saucecloud/retry/junitretrier_test.go
Prevent `panic: assignment to entry in nil map` when there is no `TestOptions` define in the config.
=> fix: JunitRetrier: Check if map is nil before updating it

cmd/saucectl/saucectl.go, internal/cmd/artifacts/cmd.go, internal/cmd/artifacts/download.go, internal/cmd/artifacts/list.go, internal/cmd/artifacts/upload.go, internal/cmd/completion/cmd.go, internal/cmd/configure/cmd.go, internal/cmd/imagerunner/artifacts.go, internal/cmd/imagerunner/cmd.go, internal/cmd/imagerunner/logs.go, internal/cmd/ini/cmd.go, internal/cmd/jobs/cmd.go, internal/cmd/jobs/get.go, internal/cmd/jobs/list.go, internal/cmd/new/cmd.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/puppeteer.go, internal/cmd/run/replay.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/cmd/signup/cmd.go, internal/cmd/storage/cmd.go, internal/cmd/storage/download.go, internal/cmd/storage/list.go, internal/cmd/storage/upload.go
On error, usage display makes it really easy to miss what actually failed.
By setting `SilenceUsage`, whenever an error occurs, no usage will be displayed, allowing to keep the actual error on sight.
=> Hide Usage when PreRun fails

internal/saucecloud/imagerunner.go
Small cleanup. Termination reason is implemented on the server side now. The check isn't needed anymore.
=> Remove obsolete termination reason check

internal/cmd/imagerunner/artifacts.go, internal/cmd/storage/upload.go, internal/fileio/temp.go, internal/files/files.go, internal/hashio/files.go, internal/hashio/files_test.go, internal/saucecloud/cloud.go, internal/saucecloud/imagerunner.go
The `files` package did not end up being a good package name. The term _files_ is a commonly used variable name, causing this package to steal a good variable name from the user and thus introducing unnecessary [variable shadowing](https://en.wikipedia.org/wiki/Variable_shadowing).
Other minor improvements were done on the way.
=> Refactor files package

go.mod, internal/framework/search_test.go
Remove unnecessary (and unmaintained) direct dependency `pkg/errors`. It is still used as an indirect dependency though.
=> Remove direct dependency pkg/errors

internal/apps/apps.go, internal/apps/apps_test.go, internal/msg/errormsg.go, internal/msg/msg.go
Remove unnecessary file check. It wasn't improving the error reporting.
With file check in place:
```sh
❯ saucectl run
16:22:48 ERR failed to execute run command error="./apps/bla.apk: file not found"
```
Without:
```sh
❯ saucectl run
16:23:22 INF Running Espresso in Sauce Labs
16:23:22 INF Checking if ./apps/bla.apk has already been uploaded previously
16:23:22 ERR failed to execute run command error="project upload: open /Users/alexplischke/devel/saucectl-espresso-example/apps/bla.apk: no such file or directory"
```
=> Remove unnecessary file check

internal/http/webdriver.go
Not a true fix but a workaround to address the video skew that we experience at high frame rates due to frame drops.
13 fps seemed to be the sweet spot that worked well for what I tested.
60 fps:
windows: https://app.saucelabs.com/tests/ee89035ffe8545edb0d6d3b4cdb9cb06
mac: https://app.saucelabs.com/tests/a05892f63bd74aee85e8949f41cb980e
13 fps:
windows: https://app.saucelabs.com/tests/19609a0e81f840fbbcb2ecdc1dfb7521
mac: https://app.saucelabs.com/tests/6eaee4dc8ae9429f92627055d2080d23
=> Fix video skew

internal/ci/ci.go, internal/ci/ci_test.go
Detect if saucectl is running in a Gitpod environment.
Additional:
- refactored to use switch-case for better readability
- removed reflection since it's not necessary
- added example as test
=> Detect Gitpod environments

go.mod, internal/apitest/config.go, internal/apitest/runner.go, internal/apitest/runner_test.go
Reduce number of calls made to retrieve project IDs. These were mostly redundant calls, since we already have the information at hand that just needed to be propagated.
=> Optimize Project ID retrieval for APIT

internal/cmd/apit/cmd.go, internal/cmd/artifacts/cmd.go, internal/cmd/imagerunner/cmd.go, internal/cmd/jobs/cmd.go, internal/cmd/run/apitest.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/imagerunner.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/cmd/storage/cmd.go
Don't track usage against staging. Causes some grief in Mixpanel, because not all internal users in staging also exist in prod. Those missing users are not correctly identified in Mixpanel and can't be easily excluded unless you exclude data tagged with the region "staging". However, staging data shouldn't even end up prod at all. So, disable usage tracking when region is staging.
=> chore: Don't track usage against staging

internal/cmd/ini/cmd.go, internal/cmd/ini/imagerunner.go, internal/cmd/ini/initializer.go, internal/cmd/ini/initializer_test.go
```
$ saucectl init 
12:15:24 INF Start Init Command
? Select region: us-west-1
? Select framework: imagerunner
? Docker Image to use: helloworld
? Set workload: webdriver
? Download artifacts: when tests are failing
The following files have been created:
.sauce/config.yml
Before running your tests, you need to set the following environment variables:
- DOCKER_USERNAME
- DOCKER_PASSWORD
```
=> chore: Set workload type when initing sauce config

internal/cmd/configure/list.go
Handle empty credentials
```
saucectl-local configure list
Credentials have not been set. Please use "saucectl configure" to set your credentials.
```
- [] Bugfix (non-breaking change which fixes an issue)
=> fix: Handle empty credentials when listing credentials

internal/imagerunner/imagerunner.go
Backend expects [workload type](https://github.com/saucelabs/hostedrunner-api/blob/main/specs/openapi_v1alpha1.yaml#L235C9-L235C9) (and anything else in image runner) to be snake case.
=> fix: Imagerunner workload type not propagated due to wrong case

internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/saucecloud/cloud.go
Skip rendering reporters when running in async mode.
=> fix: Skip rendering JUnit&JSON reporters when running in async mode

api/saucectl.schema.json, api/v1alpha/framework/imagerunner.schema.json, internal/imagerunner/config.go, internal/saucecloud/imagerunner.go
Allow additional runner metadata to be set by the user. Mainly for troubleshooting reasons to activate/deactivate certain features if or when requested by Sauce Labs.
I consolidated some parts of the code so it's a bit less spread with regards to where values are defaulted.
=> feat: Allow additional runner metadata to be set by the user

internal/archive/zip/zip.go, internal/archive/zip/zip_test.go
When zip archiving a directory, explicitly include the root directory and all sub-directories in the archive.
For most situations, this will have zero effect since during unarchiving all implicit sub-directories will be created, but this change makes the behaviour more inline with other zip utilties, including `zip` and `Archive Utility.app` on Mac.
Where it will make a difference is when executing on Sauce: the unarchiving helper functions have a "convenience" feature where it will return the path to the root dir of the archive's contents, if and only if, the first entry of the zip file directory is the prefix for all included files.
So given this directory structure:
```
root/
├── 1.txt
└── sub/
└── 2.txt
```
The current zip implementation will have the contents:
```
root/1.txt …
```
=> Include directories in zip files

internal/archive/zip/zip.go
When triggering tests on a Mac platform from a Windows machine, there is an issue with unzipping packages that have an `@` prefix in the node_modules zip.
Passed job: https://app.saucelabs.com/tests/979a262f57724f80b45de70392039333
After:
=> fix: Fix Windows zip file

internal/archive/zip/zip.go
Retain the original file's headers when zipping it up. Doing this means that the file will retain certain information, like its modification date and permissions.
=> feat: Retain file headers when zipping files

.sauce/xcuitest.yml, internal/xcuitest/config.go
`platformName` for xcuitest has only one possible value, `iOS`. Remove it from configs and set a default value to match espresso emulator behaviour.
`platformName` is **not** currently defined in the json schema for the `simulators` array so no changes needed there.
=> fix: Set platformName for simulators

api/saucectl.schema.json, api/v1alpha/framework/xcuitest.schema.json, internal/saucecloud/xcuitest.go, internal/xcuitest/config.go, internal/xcuitest/config_test.go
Add additional `testOptions` for xcuitest on simulators.
SauceCTL Test option input | xcodebuild command | Notes
-- | -- | --
testTimeoutsEnabled: "Yes\|No" | -test-timeouts-enabled [YES \| NO] | By default there is no timeout, if enabled, then the timeout is 600 seconds. This can be changed by adding the defaultTestExecutionTimeAllowance value. See also https://developer.apple.com/documentation/xctest/xctestcase/3526064-executiontimeallowance
defaultTestExecutionTimeAllowance: 200 //in seconds | -default-test-execution-time-allowance seconds | The default execution time an individual test is given to execute if test timeouts are enabled. See also https://developer.apple.com/documentation/xctest/xctestcase/3526064-executiontimeallowance
maximumTestExecutionTimeAllowance 300 // in seconds …
=> feat: Add additional testOptions for xcuitest

internal/espresso/config.go, internal/xcuitest/config.go
Classic mistake that can easily happen in go. Values vs. pointers. `otherApps` wasn't set properly due the use of a copy-value reference, rather than the pointer. I changed the loops in both espresso and xcuitest and removed the copied value entirely, so that it's less likely to happen again.
=> fix: Missing default otherApps

internal/junit/junit.go, internal/saucecloud/retry/junitretrier.go
A separation of concerns refactor with no functional changes.
Main changes are:
- [08d158fef88ff4764917508354045db0d9ef1552](https://github.com/saucelabs/saucectl/commit/08d158fef88ff4764917508354045db0d9ef1552): These framework specific details are not relevant to the junit domain. The retrier specifically or `saucecloud` package on a broader level, are the ones that need to deal with this. It's where framework or cloud implementation specific details are handled. This move reduces the implicit coupling between the two. Now it's one-sided: `saucecloud` -> `junit`.
- https://github.com/saucelabs/saucectl/commit/d3cf20d3681ac0a9ab9cb968a5e4fa1d3626660e: This function felt more native as a method.  `CollectTestCases` is something that could be done on multiple levels (TestSuites, …
=> chore: junit separation of concerns

internal/apitest/runner.go, internal/job/starter.go, internal/report/junit/junit.go, internal/report/junit/junit_test.go, internal/report/report.go, internal/report/table/table.go, internal/report/table/table_test.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/imagerunner.go
Rather than tracking attempts numerically (i.e. some counter), give the attempt a proper entity with which it can track its metadata, rather than sprinkling the metadata loosely across multiple fields (see previous "attempts" and "ParentJunits" field).
=> chore: Refactor attempt tracking

api/saucectl.schema.json, api/v1alpha/subschema/reporters.schema.json, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/cypress/config.go, internal/cypress/v1/config.go, internal/cypress/v1alpha/config.go, internal/report/spotlight/spotlight.go, internal/report/spotlight/spotlight_test.go, internal/saucecloud/cloud.go, internal/usage/tracker.go
The new spotlight reporter enhances the test summary with additional highlights (hence the name, spotlight) for a quicker UX when it comes to troubleshooting failing (or otherwise interesting) tests.
```
Spotlight:
✖ Firefox Win
● URL: https://app.saucelabs.com/tests/8518d9a0550e4ee3a82245ffa8e3127d
● Failed Tests: (showing max. 5)
✖ demo-todo-app.spec.js › New Todo › should clear text input field when an item is added
Results:
Name                                Duration    Status    Browser        Platform      Attempts
────────────────────────────────────────────────────────────────────────────────────────────────────────
✖    Firefox Win                             1m4s    failed    firefox 115    Windows 11           1
────────────────────────────────────────────────────────────────── …
```
=> feat: Add spotlight reporter

internal/cmd/storage/cmd.go, internal/cmd/storage/delete.go, internal/http/appstore.go, internal/http/appstore_test.go, internal/saucecloud/retry/saucereportretrier_test.go, internal/storage/storage.go
Add storage delete command.
```
❯ saucectl storage delete -h
Delete a file from Sauce Storage.
Usage:
saucectl storage delete <fileID> [flags]
Flags:
-h, --help   help for delete
Global Flags:
--disable-usage-metrics   Disable usage metrics collection.
--no-color                disable colorized output
-r, --region string           The Sauce Labs region. Options: us-west-1, eu-central-1. (default "us-west-1")
--verbose                 turn on verbose logging
```
=> feat: Add storage delete command

api/saucectl.schema.json, api/v1alpha/framework/xcuitest.schema.json, internal/cmd/run/run.go, internal/http/webdriver.go, internal/job/starter.go, internal/saucecloud/xcuitest.go, internal/xcuitest/config.go
Add support for defining env vars for xcuitest.
=> feat: Enable env vars for xcuitest

internal/apitest/config.go, internal/cmd/run/run.go, internal/cucumber/config.go, internal/cypress/v1/config.go, internal/cypress/v1alpha/config.go, internal/imagerunner/config.go, internal/playwright/config.go, internal/testcafe/config.go, internal/xcuitest/config.go
Previously, when setting environment variables via the `--env` flag, the root-level environment variables would be dropped. This pull request ensures that the `--env` flag and root-level environment variables can coexist.
Precedence: `--env` flag > root-level environment variables > suite-level environment variables.
=> fix: Support --env flag and root env vars simultaneously

internal/http/webdriver.go, internal/job/starter.go, internal/saucecloud/espresso.go, internal/saucecloud/xcuitest.go
Add `testApp` to VDC capabilities. On retrieval, this field still ends up in `base_config`, but unlike `testFile`, which is further nested under `batch`, it is less likely to be truncated when retrieving the metadata via the jobs API.
It is now also closer (hierarchically) to its siblings, `app` and `otherApps`.
=> feat: add testApp in metadata for mobile tests

internal/cmd/run/imagerunner.go, internal/saucecloud/imagerunner.go
Add `--async` support for imagerunner:
```
❯ saucectl run -c .sauce/imagerunner.yml --async
13:48:02 WRN A new version of saucectl is available (v0.163.0)
13:48:02 INF Launching workers. concurrency=2
13:48:02 INF Starting suite. image=busybox:1.35.0 suite="busybox num 1"
13:48:04 INF Started suite. image=busybox:1.35.0 runID=01289b0ddc3446b6b4b165f7c0b58248 suite="busybox num 1"
Name                              Duration    Status     Attempts
──────────────────────────────────────────────────────────────────────────
*    busybox num 1                           1s    Pending           1
──────────────────────────────────────────────────────────────────────────
*    All suites have launched                1s
```
=> feat: add async support for imagerunner

internal/http/imagerunner.go, internal/imagerunner/imagerunner.go, internal/saucecloud/imagerunner.go
Ensure that imagerunner startup errors are properly reported back to the user.
Here is an example of launching with invalid image pull credentials **before** this PR:
```
❯ saucectl run
07:55:40 WRN A new version of saucectl is available (v0.164.0)
07:55:40 INF Launching workers. concurrency=2
07:55:40 INF Starting suite. image=europe-west3-docker.pkg.dev/sauce-hto-p-jy6b/abn-amro-sauce/saucelabs-wiremock-dynamic-instance:latest suite="Testing Image Credentials"
Name                              Duration    Status    Attempts
─────────────────────────────────────────────────────────────────────────
✖    Testing Image Credentials               1s                     1
─────────────────────────────────────────────────────────────────────────
*    All suites …
```
=> fix: properly report imagerunner startup errors

internal/cmd/run/run.go, internal/report/buildtable/buildtable.go, internal/report/json/json.go, internal/report/report.go, internal/saucecloud/cloud.go
Add `buildURL` in each job's details.
The JSON report will like
```
[
{
"name": "saucy barista - specify device by id",
"duration": 15369633708,
"startTime": "2023-10-31T20:19:54.975575-07:00",
"endTime": "2023-10-31T20:20:10.345318-07:00",
"status": "failed",
"platform": "Android",
"deviceName": "LG_Q6_real_us",
"url": "https://app.saucelabs.com/tests/1f2f60dce5314e10b422e0d87bf2a465",
"origin": "sauce",
"buildURL": "https://app.saucelabs.com/builds/rdc/f2157d6dd70e3ae1b7c265d417a785ae"
},
{
"name": "saucy barista - test size",
"duration": 57726330417,
"startTime": "2023-10-31T20:19:54.976777-07:00",
"endTime": "2023-10-31T20:20:52.703524-07:00",
"status": "passed",
"platform": "Android 11.0",
"deviceName": "Android GoogleApi Emulator",
"url": …
```
=> feat: Add buildURL in JSON report

api/saucectl.schema.json, api/v1alpha/framework/imagerunner.schema.json, api/v1alpha/subschema/reporters.schema.json, internal/cmd/run/imagerunner.go, internal/http/resto.go, internal/imagerunner/config.go, internal/report/json/json.go, internal/report/report.go, internal/saucecloud/imagerunner.go
Add JSON reporter for  Sauce Orchestrate.
The report body will be like
```
[
{
"name": "WebdriverIO in ImageRunner",
"duration": 797308834,
"startTime": "2023-11-03T10:11:50.528903-07:00",
"endTime": "2023-11-03T10:11:51.326215-07:00",
"status": "Failed",
"platform": "Linux"
},
{
"name": "WebdriverIO in ImageRunner2",
"duration": 46294290083,
"startTime": "2023-11-03T10:11:50.528719-07:00",
"endTime": "2023-11-03T10:12:36.823238-07:00",
"status": "Succeeded",
"platform": "Linux",
"artifacts": [
{
"filePath": "artifacts/WebdriverIO_in_ImageRunner2/app/artifacts/screenshots/example-screenshot.png"
}
],
"runID": "c07e80f2b41e4b6e823c6c4fb0d2630b"
}
]
```
=> feat: Add JSON reporter for Sauce Orchestrate

internal/saucecloud/cloud.go
Stopping a job via the jobs api is async. So even though saucectl requests to stop a job when the client timeout is reached, the job's actual status is unknown; it may still be running by the time saucectl wants to report to insights or retrieve assets.
This doesn't cause an actual error, but leads to confusing and unnecessary log output where operations that are known to fail are visible to the user.
=> fix: Better logging for timed out jobs

internal/region/region.go
Allow user defined regions by reading a file at `~/.sauce/regions.yml` that defines a list of regions, e.g.:
```yaml
- name: local
apiBaseURL: "https://local-api"
appBaseURL: "https://local-app"
webdriverBaseURL: "https://local-wd"
```
=> feat: Support custom regions

internal/cmd/run/apitest.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/imagerunner.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/region/region.go, internal/region/region_test.go
Allow defining credentials for both built-in and custom defined regions.
* All sauce regions will still default to env vars and `~/.sauce/credentials.yml` by default but can be overridden in `regions.yml` like so:
```yaml
- name: us-west-1
credentials:
username: customUser
accessKey: customKey
```
* Since even sauce regions can be overridden, there is no longer global default credentials. So clients now access credentials from the configured region instead of the `credentials` package.
[DEVX-2637]
[DEVX-2637]: https://saucedev.atlassian.net/browse/DEVX-2637?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Support regional credentials

internal/apps/apps.go, internal/apps/apps_test.go, internal/saucecloud/cloud.go
Makes app storage references work when using filenames + xcuitest simulators.
Also:
- minor refactor that aligns the lingo between the functions `IsStorageReference` and `NormalizeStorageReference`.
=> fix: app storage filename references for xcuitest simulators

internal/cmd/run/run.go
Deprecate the flag `uploadTimeout` and introduce its replacement `upload-timeout`. The new flag is now consistent with the case we use for other global flags.
=> chore: deprecate flag uploadTimeout

internal/cmd/run/run.go
Remove the long since deprecated and unused flag `tunnel-id`.
=> chore!: remove deprecated flag tunnel-id

internal/cmd/ini/cmd.go
Ensure that the proper error message is returned when the region is not set.
Before:
```
❯ saucectl init playwright --no-prompt
4 errors occured:
- no playwright version specified
- no platform name specified
- no browser name specified
- Get "/v2/testcomposer/frameworks?frameworkName=playwright": unsupported protocol scheme ""
```
After:
```
❯ saucectl init playwright --no-prompt
12:40:58 ERR failed to execute init command error="no sauce region set"
```
=> fix: init region requirement for no-prompt mode

.sauce/testcafe.yml, api/saucectl.schema.json, api/v1alpha/framework/testcafe.schema.json, internal/cmd/run/testcafe.go, internal/testcafe/config.go
This PR should be merged&released after https://github.com/saucelabs/sauce-testcafe-runner/pull/197 release. It's for adding `configFile` setting to `testcafe` section.
Without this change, TestCafe can still pick up default config files which are `.testcaferc.json`, `.testcaferc.js`, `.testcaferc.cjs`.
=> feat: Support setting reporters for TestCafe

internal/cmd/run/xcuitest.go, internal/saucecloud/retry/junitretrier.go, internal/saucecloud/retry/junitretrier_test.go
In the current JUnit report, the `classname` follows the `class.testMethod` pattern. However, this format is not suitable for filtering out failed tests in smart retry tests. This PR is proposed to update the `classname` to the `class/testMethod` format.
Initial test: https://app.saucelabs.com/tests/fb0d832bc6d644c58beebe1415d229c5#1
Retried test: https://app.saucelabs.com/tests/b6d20f0fd20345bea7eb463d1e7f105c#1
Verified, real device test remains unaffected.
=> fix: Fix smart retry in XCUITest simulator test

.github/workflows/codeql.yml, .github/workflows/docker-release.yml, .github/workflows/pull-request-linter.yml, .github/workflows/release.yml, .github/workflows/test.yml, README.md
We already require to run tests on every PR and require PRs to be up-to-date with the main branch before merging. Meaning, the final fully integrated changes are properly tested on the PR before they're merged. As such, there's no need to re-test everything on the main branch yet again (💸 ).
With the addition of `workflow_dispatch:` it's still possible to run the Test workflow manually on any branch, should the need arise.
Also:
Minor renaming of the workflows for readability.
=> ci: optimize test pipeline

internal/cmd/imagerunner/cmd.go, internal/cmd/imagerunner/logs.go
The `--live-logs` flag that was intended for `saucectl imagerunner logs --live-logs` was incorrectly scoped as a global flag and thus available on all `saucectl imagerunner` subcommands.
Additionally, the flag was renamed (breaking change) to remove stutter `logs --live-logs` vs `logs --live`.
PS: This does not affect `saucectl run --live-logs` and as such, a relatively small breaking change.
=> fix!: correctly scope flag

internal/cmd/docker/cmd.go, internal/cmd/imagerunner/cmd.go, internal/cmd/imagerunner/logs.go, internal/cmd/run/imagerunner.go, internal/http/imagerunner.go, internal/imagerunner/async.go, internal/imagerunner/errors.go, internal/saucecloud/imagerunner.go
Try to improve code quality and clarity of the cloudevent handling logic (e.g. live-logs).
No business logic changes per se, but some methods were more drastically altered than others (some inversion of booleans, consolidation or breaking apart methods) which results in internal logical changes of the program.
Out of Scope:
`imagerunner/async.go` contains code to handle cloudevents and websockets. As this is code that's more related to HTTP than ImageRunner itself, I'd love to move this to the `http` package, but not in this PR.
PS: I recommend going through the individual commits, so as to better understand the changes (I know, it's plenty!).
=> refactor: improve imagerunner cloudevent handling

internal/cmd/imagerunner/cmd.go, internal/cmd/imagerunner/list.go, internal/http/imagerunner.go
Add cli to list containers:
```
$ saucectl imagerunner list -o text
┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐
│ ID                                Image                                            Status     CreationTime               TerminationTime           │
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ 44d3a9a52d0c4df2ba56f5900d42805d  saucelabs/imagerunner-playwright-example:latest  Cancelled  2024-01-25T17:03:07-08:00  2024-01-25T17:03:18-08:00 │
│ b8b79cd4e2fe4c6b9bab2924fb56821e  saucelabs/imagerunner-playwright-example:latest  Succeeded  2024-01-25T16:23:47-08:00 …
```
=> feat: Add cli to list imagerunner containers

internal/cmd/artifacts/list.go, internal/cmd/artifacts/upload.go, internal/cmd/configure/cmd.go, internal/cmd/imagerunner/artifacts.go, internal/cmd/ini/common.go, internal/cmd/ini/imagerunner.go, internal/cmd/jobs/get.go, internal/cmd/jobs/list.go, internal/cmd/storage/delete.go, internal/cmd/storage/list.go
In several places, our code currently utilizes `println()` for outputting information.
However, `println()` is primarily meant for bootstrapping and debugging purposes, and it directs output to stderr. For standard output, we should switch to using `fmt.Println()`.
=> fix: Switch to using fmt.Println

internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/http/rdcservice.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/jobservice.go
This change introduces the ability for saucectl to automatically _attempt_ to stop a timed out RDC job. It was already doing this for VDC.
I emphasize the word _attempt_ here, because I also changed the wording in the implementation (both RDC/VDC), as there are too many state related edge cases where the device, be it real or virtual, seemingly cannot be stopped. Anecdotally, during my testing, the platform negatively responded to my stop request, only to actually stop the job a few moments later with the UI properly showing that the job was stopped by the user.
=> feat: attempt to stop rdc jobs on timeout

internal/saucecloud/retry/junitretrier.go, internal/saucecloud/retry/junitretrier_test.go
Fixes regression introduced in https://github.com/saucelabs/saucectl/pull/873.
=> fix: junit retry regression for xcuitests in rdc

.github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/test.yml
CodeQL seems to have its own go version. This can cause an issue when its version and the project's version differ:
PS: I tried to switch our "manual" version setting to that of a the go.mod file, [like documented here](https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file). Could not get it to work though (as you can see by my fruitless commits).
=> ci: setup go before running codeql

.github/workflows/bump.yml, .github/workflows/release.yml
Add a new workflow to manually bump the version and create a new github release. Once the release and corresponding tag are created, the normal release workflow will be triggered.
I made the input a selection instead of a text box. I'm flip flopping between that and just a text input. No strong opinions either way.
[DEVX-2727]
[DEVX-2727]: https://saucedev.atlassian.net/browse/DEVX-2727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> build: add workflow to auto bump version

internal/imagerunner/imagerunner.go, internal/saucecloud/imagerunner.go
When a run on sauce orchestrate fails such that no logs or artifacts are available, saucectl still tries to download these assets when the run concludes. The API used to poll the job has information about the status of those assets. So use that info to skip asset download as needed.
[DEVX-2759]
[DEVX-2759]: https://saucedev.atlassian.net/browse/DEVX-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Don't try to download assets and logs if none are available

api/saucectl.schema.json, api/v1alpha/subschema/sauce.schema.json, internal/apitest/runner.go, internal/cmd/run/run.go, internal/config/config.go, internal/flags/binder.go, internal/saucecloud/cloud.go, internal/saucecloud/cucumber.go, internal/saucecloud/cypress.go, internal/saucecloud/espresso.go, internal/saucecloud/imagerunner.go, internal/saucecloud/playwright.go, internal/saucecloud/replay.go, internal/saucecloud/testcafe.go, internal/saucecloud/xcuitest.go, internal/tunnel/tunnel.go
Make the tunnel readiness timeout configurable via flags and config.
Examples:
```
❯ saucectl run --tunnel-name meow --tunnel-timeout 10s
14:24:57 INF Running Testcafe in Sauce Labs
14:24:57 INF Performing tunnel readiness check... timeout=10s tunnel=meow
14:25:08 ERR failed to execute run command error="tunnel not found"
```
```
❯ saucectl run --tunnel-name meow --tunnel-timeout -3s
14:28:55 INF Running Testcafe in Sauce Labs
14:28:55 ERR failed to execute run command error="tunnel timeout must be greater than 0"
```
=> feat: allow tunnel timeout configuration

.goreleaser.yml
`brews.folder` [has been deprecated](https://goreleaser.com/deprecations/#brewsfolder).
=> build: replace deprecated goreleaser setting

api/saucectl.schema.json, api/v1/subschema/npm.schema.json, api/v1alpha/subschema/npm.schema.json, internal/config/config.go
Support npm auth fields:
- `auth`
- `username`
- `password`
- `email`
=> feat: Support more npm registry auth fields

internal/imagerunner/config.go
The main container and the service container can each have a different resource profile. The current logic accidentally applies the main container's resource profile on the service container.
=> fix: apply correct resource profile to service containers

.github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/test.yml, Dockerfile, go.mod
Use Go 1.22.
Notes:
Our pipeline failed because it didn't meet the test coverage threshold, as detailed here: [GitHub Actions Log](https://github.com/saucelabs/saucectl/actions/runs/9103170213/job/25024429237?pr=909).
This issue arose due to changes in Go 1.22, which updated how test coverage reports are generated. Previously, Go did not include packages without test files in coverage calculations. With Go 1.22, these packages are now counted, each showing 0% coverage, causing our test coverage in `saucectl` to drop from around 43% to 34%. While this provides a more realistic measure of coverage.
Talked with @alexplischke , as we've discussed repeatedly, test coverage is merely a numerical metric and does not accurately reflect the true quality of the product. Therefore, we should …
=> build: Use Go 1.22

.github/workflows/codeql.yml, .github/workflows/release.yml, .github/workflows/test.yml
Some hygiene for the pipelines which also addresses previous warnings that the actions were giving us.
In Summary:
- The lint job had the wrong step order of checkout vs. go code setup, which caused the setup to not utilize its dependency cache, because that requires the `go.sum` file and the checkout step has obviously not happened yet.
- Speaking of cache, the modules are cached by default since `v4`.
- Pin the version of goreleaser to the current major version, for obvious reasons.
- `golangci-lint-action` was fairly outdated and was still using Node.js 16
=> ci: pipeline hygiene

internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/usage/tracker.go
Job data is not usually available when collecting usage leading to inaccurate reports.
[DEVX-2839]
[DEVX-2839]: https://saucedev.atlassian.net/browse/DEVX-2839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(reporting): Remove jobs data from usage collection

go.mod, go.sum, internal/cmd/docker/push.go
Use progress spinner to display docker output.
The output from the Docker API consists of groups of steps, each group having an identical ID and logging in parallel. 
Use a spinner to display steps without detailed progress and a progress bar to show the progress of the pushing status.
Output:
```
$ saucectl-local docker push us-west4-docker.pkg.dev/sauce-hto-p-jy6b/sauce-devx-team-sauce/devx-test:3.0
Pushing 7e0d10e4156a 100% [=============================================================================>] (62 kB/s)
Pushing 9c7bbe04a91a 100% [=============================================================================>] (24 MB/s)
Pushing 666ebea2205a 100% [==============================================================================>] (54 B/s)
Pushing e53a50d4c628 100% …
```
=> feat: Use progress bar to display docker output

internal/human/bytes.go, internal/human/bytes_test.go, internal/saucecloud/zip/archive.go, internal/saucecloud/zip/archive_test.go
The main highlight of this PR is to allow the expansion of package.json files inside `npm.dependencies` (not `npm.packages`).
As a bonus UX improvement, certain log lines will now use human readable units, which makes it easier for the user to spot mistakes or oddities at runtime:
```
10:21:31 INF Archive created. duration=2s fileCount=5232 longestPathLength=136 size="21 MB"
```
=> feat: expand package.json files in npm.dependencies

api/saucectl.schema.json, api/v1/subschema/reporters.schema.json
The v1 schema for reporters, which is just Cypress at the moment, should be identical to v1alpha. Because they have drifted apart, the current validation complains if a user tries to specify the `spotlight` reporter.
=> fix: reporters v1 api schema

api/saucectl.schema.json, api/v1alpha/framework/xcuitest.schema.json, internal/config/config.go, internal/flags/simulator.go, internal/http/webdriver.go, internal/job/starter.go, internal/saucecloud/cloud.go, internal/saucecloud/espresso.go, internal/saucecloud/xcuitest.go
Add ARM simulator support for xcuitest:
```yaml
suites:
- name: "saucy xcuitest - sims"
timeout: 10m
simulators:
- name: "iPhone 15 Simulator"
armRequired: true
platformVersions:
- "17.0"
```
PS: Unable to verify this functionality until platform is ready
```
15:27:45 ERR Failed to start suite. error="job start failed (400): UnsupportedPlatform - no images found for the specified caps" suite="saucy xcuitest - sims"
```
=> feat: ARM simulator support for xcuitest

.github/workflows/release.yml
`actions/cache@v3` is still using Node.js 16, which will soon cease to function on GitHub.
`actions/cache@v4` runs on Node.js 20.
=> ci: upgrade actions/cache@v4

internal/sauceignore/files.go, internal/sauceignore/matcher.go
`ExcludeSauceIgnorePatterns()` would perform a gitignore match against the filename, which is a relative path, that was “correctly” split according to the OS file path separator—a back-slash on Windows. However, if filename is a forward-slash path (which is actually the case in our code!), then the split will fail on Windows, resulting in a singular forward-slash path wrapped in an array being passed into the matcher, which causes a reverse-gitignore pattern to unintentionally match.
E.g. this will return `true` on windows:
```go
package main
import (
"fmt"
"github.com/go-git/go-git/v5/plumbing/format/gitignore"
)
type Matcher struct {
matcher gitignore.Matcher
}
func (m *Matcher) Match(path []string, isDir bool) bool {
return m.matcher.Match(path, isDir)
}
func main() {
matcher := …
```
=> fix: sauceignore pattern matching on windows

internal/espresso/config.go, internal/msg/errormsg.go, internal/xcuitest/config.go
SauceConnect tunnels are now supported in US-East, this condition must be removed in order to allow their usage in that region.
=> chore: Remove condition that denies using tunnels in US-East

internal/cypress/v1/config.go
Start migrating users away from the `cypress.reporters` configuration in favour of configuring reporters via their cypress config.
[DEVX-2914]
[DEVX-2914]: https://saucedev.atlassian.net/browse/DEVX-2914?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add warning about cypress.reporters

internal/cucumber/config.go, internal/cypress/v1/config.go, internal/msg/errormsg.go, internal/playwright/config.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/retry/junitretrier.go, internal/saucecloud/retry/junitretrier_test.go, internal/saucecloud/retry/saucereportretrier.go, internal/saucereport/saucereport.go, internal/testcafe/config.go
The Sauce platform distinguishes failures from errors. Failures to tend indicate test failures, aka assertion failures. Errors on the other hand are more “fatal” and pertain to the execution of the Job itself.
Our investigation has shown that if a job errors, it's safer to not rely on a test framework's test report for the specific use case of failed-test-filtering via _smart retry_, because the report itself may not contain all tests that were supposed to run and only results up to the point of failure. Saucectl would then retry the failed test(s), but the unexecuted tests will remain unexecuted.
With this change, _smart retry_ will retry errored jobs much a like a regular retry, without any "smart filtering".
=> feat: skip smart retry on errored jobs

.goreleaser.yml, internal/cmd/docker/push.go, internal/cmd/ini/initializer_test.go, internal/cmd/run/cypress.go, internal/cmd/run/playwright.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/config/config.go, internal/cypress/config.go, internal/cypress/v1/config.go, internal/http/proxy.go
Update the `strictSSL` field to a boolean pointer to distinguish between three states: not set, `true`, or `false`.
When it's not set, the npm `strictSSL` default value of `true` will be used. 
`strictSSL` not set: https://app.saucelabs.com/tests/22db9a3effdc4d9cbd005839403df483
`strictSSL` is true: https://app.saucelabs.com/tests/5a57b6dc937c447ea22852c63d5d97c7
`strictSSL` is false: https://app.saucelabs.com/tests/1ac681507c9a4a8da2f14b1deb6169d9
This update should be merged after chef release. 
sauce-runner-utils updates: https://github.com/saucelabs/sauce-runner-utils/pull/76
Besides, mark `npm.registry` field as deprecated.
=> fix!: Update npm.strictSSL behavior

internal/cmd/artifacts/cmd.go, internal/cmd/ini/initializer.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/http/rdcservice.go, internal/http/rdcservice_test.go, internal/http/resto.go, internal/saucecloud/downloader/downloader.go, internal/saucecloud/downloader/downloader_test.go
The implementation for downloading artifacts was duplicated between resto client and  rdc service client. Move downloading to a separate package to reduce duplication, maintain a better separation of concerns, and make it easier for the incoming change to downloading logic.
[DEVX-3006]
[DEVX-3006]: https://saucedev.atlassian.net/browse/DEVX-3006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> refactor: Encapsulate artifact downloading

api/saucectl.schema.json, api/v1/subschema/artifacts.schema.json, api/v1alpha/subschema/artifacts.schema.json, internal/cmd/run/run.go, internal/config/config.go, internal/job/job.go, internal/mocks/download.go, internal/report/report.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/cypress_test.go, internal/saucecloud/downloader/downloader.go, internal/saucecloud/downloader/downloader_test.go, internal/saucecloud/jobservice.go
Add an option, `allAttempts`, to download matching artifacts for all job attempts. Downloads are grouped by suite name and retries will use the existing logic to prevent collisions (i.e. a numbered suffix is attached to the suite name). Since there could be a large number of downloads for a job and its retries, the downloading now happens after the job has executed.
[DEVX-3006]
[DEVX-3006]: https://saucedev.atlassian.net/browse/DEVX-3006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add option to download matching artifacts for all job attempts

internal/job/job.go, internal/mocks/download.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/cypress_test.go, internal/saucecloud/downloader/downloader.go, internal/saucecloud/downloader/downloader_test.go, internal/saucecloud/jobservice.go
The root cause is that when setting retries and downloading artifacts simultaneously, the code determines whether to proceed with the download by checking `AllAttempts` and whether it's the last attempt (`attempts < total retries`).
However, if the job doesn’t run out of retries (e.g., if the first job has passed or the job passes threshold before hitting the retry limit), the number of attempts is smaller than the total retries, leading to the download being skipped.
To fix this issue, I updated the download function as we've known if the job is the last attempt.
This solves https://github.com/saucelabs/saucectl/issues/939 and https://github.com/saucelabs/saucectl/issues/938
=> fix: Should download artifacts when no retries

internal/http/testcomposer.go, internal/http/testcomposer_test.go
Use retryable HTTP client for test-composer request.
=> refactor: Make test-composer HTTP client retryable

Makefile
Don't force a `GOBIN` folder onto other developers. Does not affect the release of saucectl, merely where the binary is placed when running `make install`.
=> build: choose your own gobin

internal/http/rdcservice.go
Support downloading `network.har` and `crash.json`.
=> feat: support downloading network.har and crash.json

.github/workflows/test.yml, .sauce/testcafe.yml, internal/espresso/config.go, internal/saucecloud/espresso.go
Define a proper data structure for the sharding configuration of Espresso.
The result is a much cleaner API that has no need for names like `getNumShardsAndShardIndex`.
This new API is now a method of `Suite` instead of a function in the espresso package. Having it this way also improves the clarity of input params, i.e. no need for `testOptions map[string]interface{}`, which is only loosely defined.
=> refactor: espresso sharding

internal/http/rdcservice_test.go, internal/http/testcomposer_test.go
Disable retries of our underlying http client when running tests.
Before
```
ok  	github.com/saucelabs/saucectl/internal/http	43.999s
```
After
```
ok  	github.com/saucelabs/saucectl/internal/http	1.529s
```
=> tests: reduce test time

internal/build/build.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/run.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/http/build.go, internal/http/build_test.go, internal/http/resto.go, internal/http/resto_test.go, internal/saucecloud/cloud.go
Improve the Builds API.
- The `Build` API was moved out of the `Resto` client, where it was falsely implemented. This API is not provided by that particular web service.
- `GetBuildID` was completely revamped to return a full `Build` struct and was aptly renamed to `FindBuild`. The `Find` prefix meant to signify the uncertainty, since Jobs don't have to be associated with Builds—and we're technically speaking performing a search.
- Determining the `Build` URL is now the responsibility of the client that returns this entity.
- The `reportInsights` function used to retrieve the `Build` URL from scratch, once per Job, which resulted in a lot of duplicate calls. It's now using the same cache that was introduced for the build report summary.
- Fixed `Build` tests that were not calling the …
=> refactor: builds

internal/cmd/artifacts/cmd.go, internal/cmd/ini/initializer.go, internal/cmd/run/apitest.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/imagerunner.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/http/client.go, internal/http/rdcservice.go, internal/http/rdcservice_test.go, internal/http/resto.go, internal/http/resto_test.go, internal/http/webdriver.go, internal/http/webdriver_test.go, internal/job/job.go, internal/mocks/job.go, internal/saucecloud/cloud.go, internal/saucecloud/jobservice.go, internal/saucecloud/jobservice_test.go, internal/saucecloud/retry/saucereportretrier_test.go
Give Jobs the same treatment that [Builds received recently](https://github.com/saucelabs/saucectl/pull/962) by moving some of the responsibilities, such as propagating the Job URL, to the clients that create them.
=> refactor: job url propagation

internal/saucecloud/cloud.go
https://github.com/saucelabs/saucectl/pull/963 moved the responsibility of providing a Job url to the clients. There was still one location that constructed its own.
Additional log statements were simplified and aligned with regards to wording.
=> refactor: redundant job url construction

internal/config/config.go, internal/config/config_test.go, internal/cucumber/config.go, internal/cypress/v1/config.go, internal/playwright/config.go, internal/testcafe/config.go
Remove `hasMultiRegistrySupport` and always print the warning msg for `npm.registry`.
=> chore: Always warn user of npm registry deprecation

internal/saucecloud/cloud.go, internal/saucecloud/cucumber.go, internal/saucecloud/cypress.go, internal/saucecloud/espresso.go, internal/saucecloud/playwright.go, internal/saucecloud/replay.go, internal/saucecloud/testcafe.go, internal/saucecloud/xcuitest.go
Worker pool creation can't fail. `error` was always `nil`. Remove return param and unnecessary error handling.
=> refactor: no err on worker pool creation

cmd/saucectl/saucectl.go, internal/cmd/storage/delete.go, internal/cmd/storage/download.go, internal/cmd/storage/list.go, internal/cmd/storage/upload.go, internal/http/appstore.go, internal/http/appstore_test.go, internal/ioctx/ioctx.go, internal/ioctx/ioctx_test.go, internal/saucecloud/cloud.go, internal/saucecloud/retry/saucereportretrier.go, internal/saucecloud/retry/saucereportretrier_test.go, internal/storage/storage.go
Introduce a global context. As is common in Go, the idea is to propagate this cancellable context wherever it may be needed.
In an effort to keep this PR reviewable, I kept the changes contained to the app storage API. In fact, only the `saucectl storage` subcommands make use of this global context.
However, any other commands will also benefit immediately, as issuing a SIGINT twice will always result in a hard exit at the top level, irrespective of whether the global context is used or not.
=> feat: cancellable storage interactions

.github/workflows/test.yml, internal/hashio/files.go, internal/saucecloud/cloud.go, internal/saucecloud/cloud_test.go, internal/saucecloud/zip/archive.go, internal/storage/storage.go
Introducing a tagging solution for the node_modules archive.
If node_modules is taggable, use the generated tag to search for an existing archive. If found, skip archiving and uploading. Otherwise, archive and process node_modules using the existing logic if it’s not taggable.
=> feat: Tag node_modules archive

internal/apitest/runner.go, internal/cmd/run/apitest.go, internal/cmd/run/cucumber.go, internal/cmd/run/cypress.go, internal/cmd/run/espresso.go, internal/cmd/run/imagerunner.go, internal/cmd/run/playwright.go, internal/cmd/run/replay.go, internal/cmd/run/testcafe.go, internal/cmd/run/xcuitest.go, internal/saucecloud/cloud.go, internal/saucecloud/imagerunner.go
Reduce logging noise by logging tunnel and region when the run starts, not with each suite.
[DEVX-3092]
[DEVX-3092]: https://saucedev.atlassian.net/browse/DEVX-3092?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Log tunnel and region once

internal/ci/ci.go, internal/insights/testrun.go
=> feat: rename CI tags

api/saucectl.schema.json, api/v1alpha/framework/xcuitest.schema.json, internal/xcuitest/config.go, internal/xcuitest/config_test.go
Add a `concurrency: testList` option to shard a suite by the items in `testListFile`.
[DEVX-3117]
[DEVX-3117]: https://saucedev.atlassian.net/browse/DEVX-3117?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Shard xcuitest suite by testList

internal/apitest/runner.go, internal/apitest/runner_test.go, internal/cmd/run/apitest.go
Propagate the global context to all API calls. This ensures that apitest executions can be cancelled via a soft interrupt (hitting ctrl-c once).
=> feat: cancellable apitest

internal/http/resto.go
A platform side change (`/assets` endpoint) moved screenshot files to the `screenshots` field. Prior to this change, saucectl was ignoring this field as it expected screenshots to appear on the root level (as do other files).
Before fix:
```
❯ saucectl artifacts list 5648b0fc31c644b78621cf006ad899b3
┌────────────────────────────────────────────────┐
│ Items                                          │
────────────────────────────────────────────────
│ index.html                                     │
│ 583f7f084ebd4ef4b73abc88b09a78e9.last-run.json │
│ log.json                                       │
│ console.log                                    │
│ config.yml                                     │
│ junit.xml                                      │
│ video.mp4 …
```
=> fix: ensure screenshots are recognized artifacts

api/saucectl.schema.json, api/v1/subschema/common.schema.json, api/v1alpha/subschema/common.schema.json, internal/cmd/run/espresso.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/job/options.go, internal/saucecloud/espresso.go, internal/saucecloud/xcuitest.go
Added new instrumentation capabilities. `saucectl` will forwards these arguments in the API call it makes to further internal services.
=> feat: support instrumentation capabilities

api/saucectl.schema.json, api/v1/subschema/common.schema.json, api/v1alpha/framework/espresso.schema.json, api/v1alpha/framework/xcuitest.schema.json, api/v1alpha/subschema/common.schema.json, internal/cmd/run/espresso.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/job/options.go, internal/saucecloud/xcuitest.go
Follow up PR to address missing review items in the original [instrumentation update](https://github.com/saucelabs/saucectl/pull/998)
=> fix: incorrect espresso and xcuitest flags

.goreleaser.yml, api/global.schema.json, api/saucectl.schema.json, api/v1alpha/framework/xctest.schema.json, internal/cmd/run/run.go, internal/cmd/run/xctest.go, internal/cmd/run/xcuitest.go, internal/http/rdcservice.go, internal/job/options.go, internal/msg/errormsg.go, internal/saucecloud/archive.go, internal/saucecloud/archive_test.go, internal/saucecloud/xctest.go, internal/saucecloud/xcuitest_test.go, internal/xctest/config.go
Adds `xctest` test type support. Unlike `xcuitest` it doesn't require a "test" `.ipa` but a `xctestrun` file which is an Apple plist format as a descriptor. Here is what the configuration looks like:
```
apiVersion: v1alpha
kind: xctest
sauce:
metadata:
build: XCUITest Basic
concurrency: 1
xctest:
app: /Users/ricardoillgen/projects/saucelabs/rdc-xcuitest-test/apps/FlutterTestApp.ipa
xcTestRunFile: /Users/ricardoillgen/projects/saucelabs/rdc-xcuitest-test/FlutterTest.xctestrun
suites:
- name: "Basic XCTest"
devices:
- name: $DEVICE_NAME
platformVersion: $PLATFORM_VERSION
artifacts:
download:
when: always
match:
- junit.xml
directory: ./
```
=> feat: Add xctest support

internal/cmd/storage/upload.go
Allow tags to be specified when uploading apps to app storage.
E.g.
`saucectl storage upload path/to/file.app --tags espresso,ci,build`
[DEVX-3160]
[DEVX-3160]: https://saucedev.atlassian.net/browse/DEVX-3160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: Add --tags flag for storage upload command

internal/junit/junit.go
When using playwright's junit reporter, [runtime annotations](https://playwright.dev/docs/test-annotations#runtime-annotations) are serialized as properties on a test case. The junit spec we based the saucectl serializer on did not define test case level properties. So when saucectl's junit reporter is configured, annotations were missing from the merged junit report.
[DEVX-3144]
[DEVX-3144]: https://saucedev.atlassian.net/browse/DEVX-3144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: Support test case level properties in junit reporter

internal/cmd/run/espresso.go, internal/cmd/run/xctest.go, internal/cmd/run/xcuitest.go, internal/config/config.go, internal/espresso/config_test.go, internal/job/options.go
Customers reported that there is currently no way to disable Instrumentation using saucectl config (the `resigningEnabled` field) on XCUITest or Espresso. I was able to repro this, and after intercepting the raw JSON sent from saucectl, I found that any config option set to `false` does not get sent through at all (as if it was omitted from config.yml).
This isn't a problem for most fields that default to `false`, but `resigningEnabled` is the odd one out, defaulting to `true`. This means there's currently no way to set this to anything other than the default value (which is a problem).
The issue seems to stem from using [omitempty](https://stackoverflow.com/questions/37756236/json-golang-boolean-omitempty) on a boolean field. A primitive boolean can't be nil, so nil values get coerced …
=> Ensure 'false' config values are passed through

cmd/saucectl/saucectl.go, internal/cmd/devices/cmd.go, internal/cmd/devices/list.go, internal/cmd/ini/initializer.go, internal/devices/devices.go, internal/devices/devicestatus/devicestatus.go, internal/http/rdcservice.go, internal/http/rdcservice_test.go, internal/mocks/devices.go
Adds `devices list` command:
```sh
$ saucectl devices list  --help
Returns the list of devices
Usage:
saucectl devices list [flags]
Aliases:
list, ls
Flags:
-h, --help                help for list
-n, --name string         Filter devices by name.
--os string           Filter devices by OS.
--os-version string   Filter devices by OS version. Accepts semver ranges.
-o, --out string          OutputFormat format to the console. Options: text, json. (default "text")
--status string       Filter devices by status. Implies --statuses if not set.
--statuses            Fetch status for devices.
Global Flags:
--disable-usage-metrics   Disable usage metrics collection.
--no-color                disable colorized output
-r, --region string           The Sauce Labs region. Options: us-west-1, …
```
=> [INT-83] add devices list command

api/saucectl.schema.json, api/v1/framework/cypress.schema.json, internal/cypress/v1/config.go
cypress reporters should be setup with the user's cypress config. Supporting cypress reporters in saucectl config has been deprecated for a while, removing support here.
[INT-171]
[INT-171]: https://saucedev.atlassian.net/browse/INT-171?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: Remove deprecated feature

tests/e2e/playwright-cucumberjs/.sauce/config.yml
`playwright-cucumber-js` used an obsolete version of `playwright`. This changes the version to the latest supported by Sauce.
=> [no-ticket] [e2e] use latest playwright version

internal/playwright/config.go
The test names could contain characters that are used by regular expressions, and were not escaped, such as:
```
[user tests] login test
```
This change makes sure to escape all tests names before passing them to the `grep` parameter.
Ref: https://saucedev.atlassian.net/browse/INT-168
=> [INT-168] playwright: escape test names before passing them to grep

api/saucectl.schema.json, api/v1alpha/framework/testcafe.schema.json
Changes `armRequired` type to `bool` instead of `string`.
=> [INT-367] testcafe: fix invalid armRequired type

api/saucectl.schema.json, api/v1alpha/framework/testcafe.schema.json
`$ref` to another `platformName` was causing the TestCafe's `platformName` enum values to be ignored.
=> [INT-438] testcafe: remove schema from platformName
