- cli/command/new/cmd.go
- cli/command/new/templates.go
- cli/docker/docker.go
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
> add testcafe to frameworks list for quick onboarding using new command

- README.md
Add documentation for saucectl commands and flags.
> Document commands and flags

- cli/docker/docker.go
- cli/runner/ci.go
Propagates sauce tags to the test framework. This allows the reporter to add the tags to the test report.
> Propagate sauce tags to the test framework

- .github/SUPPORT.md
Adding such a file helps user to understand what kind of support we provide for this OSS project. I set the request time SLA to 48h. This should be decided with the team and I am happy to modify it.
n/a
> Adding a SUPPORT.md file

- cli/command/new/cmd.go
- cli/command/new/templates.go
- cli/docker/docker.go
As saucelabs/stt-cypress-mocha-node container was released we want to update saucectl new command to enable cypress templates. 
- [] Lint and unit tests pass locally with my changes
- [] I have added tests that prove my fix is effective or that my feature works
- [] I have added necessary documentation (if appropriate)
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and …
> Add cypress framework

- cli/command/run/cmd.go
- cli/config/config.go
- cli/docker/docker.go
- cli/docker/docker_test.go
- cli/mocks/runner.go
- cli/runner/ci.go
- cli/runner/local.go
- cli/runner/runner.go
- cli/runner/runner_test.go
Working towards config variant 2.
This requires some changes to how saucectl organizes and passes around test information for what constitutes a test run.
To avoid large, hard to review changes within a massive PR, the changes are broken down into many small PRs.
> Rename JobConfiguration to Project

- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/test.yml
- cli/docker/docker.go
- cli/progress/progress.go
- cli/testcomposer/testcomposer.go
This PR fixes remaining lint issues and enforces checks in the pipeline.
Also updates the PR template to hide comments properly.
> Enforce lint

- cli/runner/ci.go
- cli/runner/local.go
- cli/runner/runner.go
- cli/runner/runner_test.go
- internal/ci/ci.go
- internal/ci/ci_test.go
Some code refactor and cleanup for the runner. This is part of the config v2 changes.
Main change is the CI environment detection, that does not rely on our internal file presence, but rather the "standard" CI environment flags.
> Detect CI environment via env variables

- cli/runner/ci.go
- cli/runner/local.go
- cli/runner/local_test.go
- cli/runner/runner.go
- cli/runner/runner_test.go
Refactor the `localrunner` into `DockerRunner` to prepare its move to the docker package (after all, it's a docker implementation of the test runner).
No functional changes.
> Rename localrunner to DockerRunner

- cli/command/run/cmd.go
- cli/runner/ci.go
- cli/runner/runner.go
- cli/runner/runner_test.go
Removes the implicit runner creation from the runner package. Instead, the `run command` creates the specific runner it wants. This will help in breaking the runner package apart.
> Create runner explicitly

- .github/workflows/test.yml
Update the pipeline's framework tests. Using the new images that have elevated access (root).
Pipelines were updated to reflect those changes and utilize github's artifact download feature.
> Update framework tests

- .github/workflows/test.yml
- .sauce/playwright.yml
Update images in the test pipeline. Run the container in github with github's user.
Both changes together result in a pipeline that doesn't need any additional workarounds.
Suites have been re-enabled and are working now.
Playwright's test has been updated to utilize firefox, just to provide some additional coverage (e.g. the root permission issue only occured in firefox).
> Update test pipeline

- CONTRIBUTING.md
- README.md
I would say information on setting up the project and run tests should be in the contribution guidelines.
> Move setup docs to contribution guidelines

- internal/docker/docker.go
- internal/docker/docker_test.go
Dont' flatten the hierarchy when copying over files (folders, in particular) in docker.
> Don't flatten the hierarchy when copying over files in docker

- internal/fpath/file.go
- internal/fpath/file_test.go
Add function to list files based on regexp patterns.
This can be later used for detecting test files based on the `match`-ing that the user specifies.
> Add function to list files based on regexp patterns

- cli/command/cli.go
- cli/command/run/cmd.go
- cli/mocks/runner.go
- cli/runner/runner.go
- internal/ci/runner.go
- internal/docker/docker.go
- internal/docker/runner.go
- internal/docker/runner_test.go
- internal/fpath/file.go
- internal/fpath/file_test.go
Part 2 of the changes to prepare saucectl for test negotiation.
These changes are purely cosmetical (refactoring) and are meant to clean up responsibilities between packages, namely the `command/run` package and the various runners.
No functional changes are present in this PR.
> Prepare Test Negotiation, Part 2

- cli/command/run/cmd.go
- cli/runner/runner.go
- internal/ci/runner.go
- internal/docker/runner.go
- internal/docker/runner_test.go
- internal/fleet/fleet.go
- internal/fleet/fleet_test.go
- internal/fpath/file_test.go
- internal/memseq/sequencer.go
- internal/testcomposer/testcomposer.go
- internal/testcomposer/testcomposer_test.go
This change adds a local test sequencer.
Tests are still executed serially, as they were before. However, each spec is now split up and run individually.
With that, we have a the following test flow:
```
Project
-> Suite 1
--> Run Test A
--> Run Test B
-> Suite 2
--> Run Test X
--> Run Test Y
```
In other words: A project is run, which in turn runs its test suites. Each test suite has a set of spec files. Each spec file will trigger an actual test run.
> Prepare for Test Negotiation Part 3

- .github/workflows/test.yml
- .sauce/puppeteer_parallel.yml
- README.md
- cli/command/run/cmd.go
- cli/command/run/cmd_test.go
- cli/config/config.go
- internal/ci/ci.go
- internal/ci/github/github.go
- internal/ci/github/github_test.go
- internal/ci/gitlab/gitlab.go
- internal/ci/gitlab/gitlab_test.go
- internal/ci/jenkins/jenkins.go
- internal/ci/jenkins/jenkins_test.go
- internal/ci/runner.go
- internal/ci/runner_test.go
- internal/docker/runner.go
- internal/fleet/fleet.go
- internal/fleet/fleet_test.go
- internal/fpath/file.go
- internal/memseq/sequencer.go
- internal/region/region.go
- internal/region/region_test.go
- tests/e2e/puppeteer-parallel/example-1.test.js
- tests/e2e/puppeteer-parallel/example-2.test.js
- tests/e2e/puppeteer-parallel/example-3.test.js
- tests/e2e/puppeteer-parallel/example-4.test.js
This PR adds support for test parallelization across machines.
The requirements are:
1. The `parallel` flag must be set to `true`, either via config or CLI args.
2. Credentials need to be set.
3. Test must be executed inside the CI.
4. The CI provider must be known, so that a correct build ID can be generated. Alternatively, the user can provide a custom ID as well.
> Add initial support for test parallelization across machines

- internal/archive/zip.go
- internal/archive/zip_test.go
> Add functions to zip project

- .sauce/cypress.yml
- .sauce/playwright.yml
- .sauce/puppeteer.yml
- .sauce/puppeteer_parallel.yml
Removes the unnecessary declaration of `capabilities` in our test configs.
> Remove obsolete declaration of capabilities

- cmd/saucectl/saucectl.go
- cmd/saucectl/saucectl_test.go
- internal/docker/docker.go
1. Use flashes for path construction when mounting files for the container (it's unix anyway).
2. Verbose logging is now `debug` and default is `info`.
> Win mount path and logging

- README.md
Add doc for filtering out suite by name
> Add doc for filtering out suite by name

- cli/command/run/cmd.go
- cli/runner/runner.go
- cli/utils/utils.go
- cli/utils/utils_test.go
- go.mod
- internal/ci/ci.go
- internal/ci/ci_test.go
- internal/ci/runner.go
> add environment variables that set runner configs

- cli/command/run/cmd_test.go
- internal/ci/runner.go
- internal/docker/runner.go
Executes the full suite (with all of the specs) instead of one spec at a time.
> Run the full suite instead of one spec at a time

- internal/fpath/file.go
- internal/fpath/file_test.go
Fixes an issues where files were executed as a test, because they were specified in the project files, despite them being excluded according to the regexp.
> Don't skip regex eval when specifying files directly

- internal/ci/runner.go
- internal/docker/runner.go
Process all suites even if one is failing
Return failed exitCode in case of any suite failing.
Relates to: https://github.com/saucelabs/testrunner-toolkit/issues/58
> Process all suites

- cli/command/configure/cmd.go
Update the signup link in the `configure` command for tracking purposes.
Separate the string with newlines so that it doesn't overflow on 80 character column common default.
e.g.:
```
❯ ./saucectl configure
10:24AM INF Start Configure Command
Don't have an account? Signup here:
https://bit.ly/saucectl-signup
Already have an account? Get your username and access key here:
https://app.saucelabs.com/user-settings
10:24AM INF failed to read credentials: open /Users/richard/.sauce/credentials.yml: no such file or directory
SauceLabs username
```
> Update configure command signup link. Fix width to not overflow 80 characters.

- README.md
- [x ] Documentation Update (if none of the other choices apply)
- [ x] I have added necessary documentation (if appropriate)
> Add Requirements section to README.md

- cli/credentials/credentials_test.go
> Saves credentials.yml config file to temp folder while running unit test

- internal/ci/runner.go
also added message to make error log more helpful (this happened because I was getting an error in `setUp` and it this message unveiled the error)
> don't run entry.sh if SAUCE_VM

- .github/ISSUE_TEMPLATE/feature.md
> Add feature proposal template

- cli/command/run/cmd.go
- internal/cypress/sauce/runner.go
Add a new, undocumented (for now) flag that specifies the test environment. Defaults to docker.
This allows for the correct workflow to be selected.
> Add Test Environment Flag

- internal/cypress/docker/docker.go
- internal/cypress/docker/runner.go
- internal/docker/docker.go
- internal/docker/docker_test.go
- internal/docker/runner.go
Console logs after changes
12:24PM INF Running version unknown-version
12:24PM INF Reading config file config=.sauce/cypress.yml
12:24PM INF Running Cypress in Docker
12:24PM INF Setting up test environment
12:24PM ERR Failed to setup test environment error="Docker image name property was not specified in your config file"
12:24PM ERR 1 suite(s) failed
> Harden docker launch workflow

- cli/command/run/cmd.go
- internal/cypress/sauce/runner.go
Run multiple suites concurrently against the sauce cloud.
Configurable via the CLI:
```
saucectl run --test-env sauce --ccy 10
```
> Cloud concurrency

- cli/config/config.go
- internal/cypress/sauce/runner.go
- internal/job/starter.go
Allows a tunnel to be specified (only relevant for running in sauce).
> Allow the user the specify a tunnel

- internal/region/region.go
Add `staging` as a region. Mainly for sauce employees to test in a pre-production environment.
> Add staging as a region

- cli/command/run/cmd.go
- internal/cypress/sauce/runner.go
- internal/job/reader.go
- internal/resto/client.go
- internal/resto/client_test.go
> Output useful test run information (for sauce cloud only)

- internal/cypress/docker/docker.go
- internal/docker/docker.go
Add image name to env in order to show platform name on UI
> Add image name to env to display platform on UI

- cli/command/run/cmd.go
- internal/cypress/sauce/runner.go
- internal/region/region.go
Replaces the URL from api.* to app.*
- [z] Lint and unit tests pass locally with my changes
> Correct URL provided when running against Sauce VM

- internal/cypress/sauce/runner.go
- internal/testcomposer/testcomposer.go
> fix showing suite as failed even though a tests has passed

- internal/testcomposer/testcomposer.go
> Update JS Framework onboarding link

- cli/command/configure/cmd.go
- cli/command/run/cmd.go
> —suite filter is not implemented for cypress

- .sauce/cypress.yml
- .sauce/cypress_cloud.yml
Documents the fileTransfer setting in our config yaml examples.
> Document fileTransfer setting for docker

- cli/command/run/cmd.go
- cli/config/config.go
- internal/cypress/config.go
Adds basic cypress config validation.
> Add basic cypress config validation

- cli/command/run/cmd.go
Reveal hidden flags for test env selection.
> Reveal hidden flags for test env selection

- internal/cypress/config.go
- internal/cypress/sauce/runner.go
> Ensure unique suite names

- README.md
Remove docs of this flag so it doesn't trip people up. It's not supported.
> Remove docs for the parallel flag

- .sauce/cypress.yml
- .sauce/cypress_cloud.yml
- internal/cypress/docker/runner.go
Prefix the docker tag version properly.
Also update the pipeline configs to make use of this new functionality.
> Fix docker tag versioning for cypress

- .github/workflows/test.yml
Elevate permissions so that framework (or scripts) can create output files that occur as part of running tests.
> Elevate test access

- .sauce/playwright.yml
- internal/playwright/config.go
- internal/playwright/sauce/runner.go
Uniformize between global/per-suite setting.
> Uniformize params/param in playwright configuration

- internal/ci/runner.go
- internal/docker/legacydocker.go
- internal/docker/legacydocker_test.go
- internal/docker/legacyrunner.go
- internal/docker/legacyrunner_test.go
Deprecate legacy implementations.
This PR is simply a refactor. No logic changes.
> Deprecate legacy implementations

- .github/workflows/test.yml
- cli/command/run/cmd.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/worker.go
Relocate the playwright cloud runner.
Minor adjustments to the console logging logic. Otherwise no logic changes, simply refactor.
> Relocate playwright cloud runner

- cli/command/run/cmd.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cloud_test.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
Consolidate suite logging and project uploading for cloud runner.
Other functions will follow in separate PRs.
> Consolidate suite logging and project uploading

- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
Consolidate project archiving.
> Consolidate project archiving

- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
Consolidate cloud job run logic.
No logic changes, simple refactor.
> Consolidate cloud job run

- internal/saucecloud/cloud.go
Indicate the archive file size.
Helps with debugging payload/upload related issues.
> Indicate archive file size

- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
Consolidate project archive preparation.
> Consolidate project archive preparation

- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/testcomposer/testcomposer.go
Remove dependency on credentials from cloud runner.
The client is taking care of that now (which is already did for other workflows).
> Remove dependency on credentials from cloud runner

- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/playwright.go
Consolidate beforeExec, suite runs, docker dependencies, execute and teardown for docker.
> Docker Runner Refactoring - 2

- cli/config/config.go
- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/playwright.go
> Consolidate image pull logic

- cli/mocks/docker.go
- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/docker.go
- internal/docker/docker_test.go
- internal/docker/playwright.go
Consolidate image setup (and pull) for docker.
> Docker Refactor - 3 

- internal/cypress/config.go
- internal/playwright/config.go
Realign versioning formatting.
The previous check was done fairly late in the process.
> Realign versioning formatting

- .sauce/cypress.yml
- .sauce/cypress_cloud.yml
- internal/config/config.go
- internal/cypress/config.go
- internal/docker/container.go
- internal/docker/docker.go
- internal/docker/docker_test.go
- internal/playwright/config.go
Flattening the image definition inside the config (new frameworks only, not for legacy).
Effectively turning this:
```
docker:
image:
name: myimage
tag: latest
```
into this:
```
docker:
image: myimage:latest
```
This change will require documentation updates across the board.
> Redefining Docker Image config

- .sauce/playwright.yml
- cli/command/run/cmd.go
- internal/cypress/config.go
- internal/docker/playwright.go
- internal/playwright/config.go
Expand env vars.
Example
```
export MY_HELLO=hello
```
in sauce config, it should expand $MY_HELLO to `hello`
> Expand env var in config files

- cli/command/run/cmd.go
- internal/cypress/config.go
- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/playwright.go
- internal/framework/framework.go
- internal/job/starter.go
- internal/mocks/job.go
- internal/playwright/config.go
- internal/saucecloud/cypress_test.go
- internal/testcomposer/testcomposer.go
- internal/testcomposer/testcomposer_test.go
Determines the appropriate docker image based on the provided framework & version.
This is done by calling the test-composer service.
Not breaking change per se, but requires credentials to set at all times.
> Automagic Docker Image Determination

- cli/command/run/cmd.go
Increase request timeouts across the board.
> Increase request timeouts

- .sauce/testcafe.yml
- internal/testcafe/config.go
> Introducing TestCafe Native Config 

- .goreleaser.yml
> Remove docker dependency

- .github/workflows/test.yml
- .sauce/testcafe.yml
- cli/command/run/cmd.go
- internal/config/config.go
- internal/docker/container.go
- internal/docker/playwright.go
- internal/docker/testcafe.go
- tests/e2e/testcafe/example.test.js
> Run testcafe with native config in docker

- internal/testcafe/config.go
Add default value for Speed (1 instead of 0).
> Add default value for speed

- .github/workflows/test.yml
Upload coverage report to codecov.
While we do have a quality gate with a coverage threshold that must be met already, we lack a visual representation of it that makes it easier to see how a PR affects the current coverage.
Adding codecov to the pipeline should address this lack of insight.
> Upload coverage report to codecov

- .github/workflows/test.yml
- cli/version/version.go
- internal/appstore/appstore.go
- internal/requesth/request.go
- internal/requesth/request_test.go
- internal/resto/client.go
- internal/testcomposer/testcomposer.go
Set custom user agent for http requests.
This helps us track saucectl versions that are in use.
> Set custom user agent for http requests

- .sauce/testcafe.yml
> Bump up testcafe framework version

- .github/workflows/test.yml
- .sauce/testcafe.yml
- .sauce/testcafe_cloud.yml
- cli/command/run/cmd.go
- cli/command/run/cmd_test.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcomposer/testcomposer.go
> Run testcafe in cloud with native config

- cli/command/new/cmd.go
> Fix generating testcafe template

- Makefile
Have `make install` actually do what it says.
> Have make install actually install

- cli/command/run/cmd.go
- internal/cypress/config.go
- internal/job/starter.go
- internal/playwright/config.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
Example:
```
saucectl run -c .sauce/cypress.yml --runner-version "github-release: v5.7.3" --test-env sauce
saucectl run -c .sauce/playwright.yml --runner-version "github-release: v1.7.4" --test-env sauce
saucectl run -c .sauce/testcafe_cloud.yml --runner-version "github-release: v0.3.1" --test-env sauce
```
> Add flag to specify runner_version in sauce cloud

- cmd/saucectl/saucectl.go
- internal/saucecloud/cloud.go
Display archive package and upload duration.
```
./saucectl run
[...]
15:32:40 INF Project archived. durationMs=4 size=60954
15:32:41 INF Project uploaded. durationMs=998 storageId=1234567-890A-BCDE-FGHI-JKLMNOPQRSTU
[...]
```
> Display archive package and upload duration

- internal/docker/container.go
Provide information that the reporting failed to be uploaded to Sauce Labs.
> Warn if reporting is not announced to be successfull

- internal/cypress/config.go
- internal/docker/cypress.go
- internal/saucecloud/cypress.go
> add rootDir to the config

- cli/command/run/cmd.go
- internal/cypress/config.go
- internal/playwright/config.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
- internal/saucecloud/playwright_test.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/testcafe_test.go
- internal/testcafe/config.go
e.g.
```
./saucectl run -c .sauce/testcafe.yml --test-env sauce --dry-run
13:37:48 INF Running version v0.0.0+unknown
13:37:48 INF Reading config file config=.sauce/testcafe.yml
13:37:48 INF Running Testcafe in Sauce Labs
13:37:48 WRN Running Testcafe test in dry run mode.
13:37:48 INF Detected following test suites: saucy test.
13:37:48 INF Project archived. durationMs=2 size=1226
13:37:48 INF Skipping project upload. Saving bundled project to sauce-app-payload-211331851/app.zip.
```
> Add dry run mode when running test in sauce env

- cli/command/new/templates.go
- internal/appstore/appstore.go
- internal/archive/zip/zip.go
- internal/archive/zip/zip_test.go
- internal/ci/runner.go
- internal/config/config.go
- internal/credentials/credentials.go
- internal/docker/container.go
- internal/docker/docker.go
- internal/docker/legacydocker/legacydocker.go
- internal/docker/legacydocker/legacyrunner.go
- internal/fpath/file.go
- internal/jsonio/file_test.go
- internal/resto/client.go
- internal/testcomposer/testcomposer.go
- internal/yaml/file.go
- internal/yaml/temp.go
`ioutil` is deprecated. Replace its usage.
> Replace ioutil usage

- internal/docker/testcafe.go
- internal/playwright/config.go
- internal/testcafe/config.go
`RootDir` is now the default folder.
When absent, it should use `ProjectPath` value.
All rest of code should be based on `RootDir` instead of `ProjectPath`
> Use RootDir value

- cli/command/run/cmd.go
- internal/config/config.go
- internal/job/starter.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
Add experiments support in saucectl.
> Add experiments support

- .github/workflows/test.yml
- internal/archive/tar/tar.go
- internal/archive/tar/tar_test.go
- internal/docker/docker.go
> Run frameworks from template

- internal/playwright/config.go
- internal/testcafe/config.go
> Fill default value for native config

- cmd/saucectl/saucectl.go
> log error and exit instead of using panic in main function

- internal/archive/tar/tar.go
Support copy mode on Windows.
Fixes #237
> windows: Support copy mode on Windows

- cli/command/run/cmd.go
Consolidate dependencies by moving them further up in the hierarchy.
This marks the first step towards a more uniform setup for the `run` command.
> Consolidate dependencies

- .sauce/espresso.yml
- internal/espresso/config_test.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
Add support for espresso TestOptions (`class`, `notClass`, `package`, `annotation`, `size`)
> Add Espresso TestOptions support

- .sauce/cypress_cloud.yml
- .sauce/espresso.yml
- .sauce/testcafe_cloud.yml
- go.mod
- go.sum
- internal/config/config.go
- internal/cypress/config.go
- internal/job/reader.go
- internal/mocks/job.go
- internal/playwright/config.go
- internal/resto/client.go
- internal/resto/client_test.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cloud_test.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
Support download of assets depending configuration
> Automated assets download

- internal/config/config.go
- internal/cypress/config.go
- internal/playwright/config.go
- internal/testcafe/config.go
> Add test mode for suite and global test mode

- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/espresso.go
- internal/saucecloud/espresso_test.go
- internal/saucecloud/playwright.go
- internal/saucecloud/playwright_test.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/testcafe_test.go
Exit `saucectl` when there is no cloud concurrency available instead of waiting.
> Exit if no concurrency available (Cloud)

- internal/saucecloud/cloud.go
It should print out some configs like following:
15:53:18 INF Suite started. device="Android GoogleApi Emulator" name="Testing Espresso Support - saucy barista" platform=Android suite=storage:250f9dee-7d0b-4024-96e9-a5f37c49bc92 url=https://app.saucelabs.com/tests/5cfa6aa96d1c459baa70e3a091d604b4
> Print out more job configs in cli

- .github/workflows/test.yml
- .sauce/cypress.yml
- .sauce/cypress_cloud.yml
- .sauce/playwright.yml
- .sauce/testcafe.yml
- cli/command/run/cmd.go
- internal/cypress/config.go
- internal/docker/container.go
- internal/espresso/config.go
- internal/playwright/config.go
- internal/saucecloud/cloud.go
- internal/testcafe/config.go
When passing mode from cli
* If mode = docker, all test suites should run in docker
* If mode = sauce, all test suites should run in sauce
When setting mode for each suite
* If mode = docker, the suite should be merged to dockerSuites
* If mode = sauce, the suite should be merged to sauceSuites
* If mode = "", the suite should run in global default mode
* Run dockerSuites and then run sauceSuites
testEnv still can be used to control the mode
> Run test in different modes

- cli/command/run/cmd.go
> Remove test-env default value

- internal/cypress/config.go
- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/playwright.go
- internal/docker/puppeteer.go
- internal/docker/testcafe.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
Previously, configuration filename was hardcoded as `sauce_config.yml`.
Now this is dynamic, based on user's filename.
> Keep config filename when uploading as asset

- cmd/saucectl/saucectl.go
- internal/msg/msg.go
- internal/sauceignore/matcher.go
Warn the user if `.sauceignore` is not present.
> Warn on missing .sauceignore file

- internal/saucecloud/testcafe.go
Removes incorrect warning message:
```
18:11:55 WRN failed to open configuration: open : no such file or directory
```
Present only for TestCafe.
> fix: Error while uploading config file (TestCafe)

- internal/resto/client.go
- internal/resto/client_test.go
> Use the newer testcomposer endpoint

- internal/playwright/config.go
In case of specifying incorrect `browserName` a user will get an error message and VM won't be started. Format of error message will be `09:46:45 ERR failed to execute run command error="browserName: chrome is not supported. List of supported browsers: chromium, firefox, webkit"`
> playwright add supported browsers check

- internal/playwright/config.go
Deprecate global playwright params.
> Depreate global playwright params

- cli/command/run/cmd.go
- internal/msg/msg.go
Adding global timeout.
Note: I re-used and redefined the previous timeout setting as it wasn't actually used (flag existed but not implemented).
> Add global timeout

- .sauce/espresso.yml
Replace `devices` field by `emulators`
> fix: Espresso configuration

- .github/workflows/test.yml
Helps to trace back artifacts produced during builds, back to the build.
> Set ldflags during test builds

- internal/saucecloud/cloud.go
Updates RDC jobs output reports from:
```
Name                               Duration    Status    Platform       Device
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖    saucy barista                           15s    failed
✔    saucy barista                           30s    passed
✔    saucy barista                           53s    passed    Android 8.1    Google Pixel C GoogleAPI Emulator
──────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖    1 of 3 suites have failed (33%)       1m39s
```
to:
```
Name                               Duration    Status    Platform       Device
──────────────────────────────────────────────────────────────────────────────── …
```
> Add report fields for RDC

- internal/msg/msg.go
Add space after docker/saucecloud banner
> add space after docker/saucecloud banner

- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
> Add sharding config for espresso

- internal/archive/zip/zip.go
- internal/saucecloud/cloud.go
- internal/saucecloud/xcuitest.go
- internal/saucecloud/xcuitest_test.go
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
Archive .app to .ipa before uploading it.
> xcuitest: pack .app to .ipa

- cli/version/version.go
- internal/github/github.go
- internal/github/github_test.go
- internal/requesth/request_test.go
Fix: False positive update du to missing `v` in version.
> fix: Support missing v in semver version

- internal/job/starter.go
- internal/saucecloud/xcuitest.go
Use the expected field for tests filtering.
> fix: XCUITest: Use testsToRun instead of TestOptions

- .gitignore
- cli/command/run/cmd.go
- cli/command/run/espresso.go
- internal/cypress/config.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
It will print out following messages
```
15:48:15 WRN Running tests in dry run mode.
15:48:15 INF The [saucy barista] suite would run on Android GoogleApi Emulator Android 11.0.
15:48:15 INF The [saucy barista] suite would run on Android GoogleApi Emulator Android 10.0.
15:48:15 INF The [saucy barista] suite would run on Google Pixel C GoogleAPI Emulator Android 8.1.
```
> Add dry run mode for espresso

- .sauce/xcuitest.yml
- cli/command/run/cmd.go
- cli/command/run/cmd_test.go
- cli/command/run/espresso.go
Add global flags for tags and build. Also re-organizes where global flags are stored, so that they are easily distinguished from other regular variables.
> Add global flags for tags and build

- cli/command/run/cmd.go
- cli/command/run/espresso.go
- internal/config/config.go
Add flags for artifact downloads.
> Add flags for artifact downloads

- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
> Add clearPackageData for espresso

- .github/workflows/test.yml
- .sauce/espresso.yml
- .sauce/espresso_light.yml
Add a test to our pipeline for configuring espresso tests on the fly.
> Add test for espresso's CLI Driven configuration

- .github/workflows/test.yml
- .sauce/xcuitest_light.yml
- cli/command/cli.go
- cli/command/run/cypress.go
- cli/command/run/espresso.go
- cli/command/run/playwright.go
- cli/command/run/puppeteer.go
- cli/command/run/run.go
- cli/command/run/run_test.go
- cli/command/run/testcafe.go
- cli/command/run/xcuitest.go
- cmd/saucectl/saucectl.go
- internal/config/config.go
- internal/cypress/config.go
- internal/espresso/config.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/testcafe/config.go
- internal/xcuitest/config.go
Add xcuitest run command `saucectl run xcuitest`.
The `run` package has been refactored further to ensure that subcommands share logic where they can.
> [DEVX-978] Add xcuitest run command

- cli/command/run/espresso.go
- cli/command/run/run.go
- cli/command/run/xcuitest.go
Reduce the global var pollution in the `run` package.
Purely refactor, no functional changes.
> Reduce global var pollution

- cli/command/init/common.go
- cli/command/init/cypress.go
- cli/command/init/espresso.go
- cli/command/init/initializer.go
- cli/command/init/initializer_test.go
- cli/command/init/playwright.go
- cli/command/init/puppeteer.go
- cli/command/init/testcafe.go
- cli/command/init/xcuitest.go
Fix post-refactor config references.
> Fix post-refactor config references

- .sauce/testcafe.yml
- internal/config/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/testcafe_test.go
- internal/testcafe/config.go
Deprecate 'devices' field for testcafe.
> [DEVX-982] Deprecate 'devices' field for testcafe

- internal/saucecloud/cloud.go
Adding log output just to validate users' selectors.
This is a small UX modification.
> Tell the user if device selection will be private

- internal/cmd/run/testcafe.go
- internal/docker/container.go
- internal/testcafe/config.go
- internal/testcafe/config_test.go
Consolidate testcafe configuration handling. Ought to reduce some of the spaghetti code that has surfaced over time.
> [DEVX-982] Consolidate testcafe configuration handling

- .sauce/xcuitest.yml
- internal/rdc/client.go
- internal/rdc/client_test.go
Generates the list of assets from job details instead of an hardcoded one.
Fixes https://github.com/saucelabs/saucectl/issues/355
> [DEVX-1050] Make asset list from RDC dynamic

- .github/workflows/test.yml
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/run.go
- internal/cmd/run/xcuitest.go
- internal/cypress/config.go
- internal/docker/container.go
- internal/espresso/config.go
- internal/espresso/config_test.go
- internal/puppeteer/config.go
- internal/testcafe/config.go
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
Add dedicated run cmd for puppeteer.
No doc updates due to CLI Driven approach still in a WIP.
> [DEVX-981] Add dedicated run cmd for puppeteer

- internal/cmd/ini/cmd.go
```
Flags:
-a, --accessKey string                 access key for the Sauce Labs account making the request
```
> [devx-1073] Fix accesskey in sauce init command

- internal/resto/client.go
See #363 
- [*] Bugfix (non-breaking change which fixes #363 363)
- [ *] Lint and unit tests pass locally with my changes
/available_tunnels will not be removed in the forceable future  so the existing saucectl versions behavior will not be affected
> Resolves  #363 

- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/espresso/config.go
- internal/xcuitest/config.go
Bind flags and config for xcuitest with viper.
> [DEVX-1070] Bind flags and config for xcuitest with viper

- internal/cmd/run/cypress.go
- internal/cmd/run/run.go
- internal/cypress/config.go
Bind flags and config for cypress with viper.
> [DEVX-1070] Bind flags and config for cypress with viper

- internal/cmd/run/espresso.go
- internal/cmd/run/run_test.go
- internal/cmd/run/testcafe.go
- internal/flags/binder.go
- internal/testcafe/config.go
Bind flags and config for testcafe with viper.
> [DEVX-1070] Bind flags and config for testcafe with viper

- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/cypress/config.go
- internal/espresso/config.go
- internal/flags/binder.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/xcuitest.go
- internal/testcafe/config.go
Handle 'run' command flags with viper. Some flags, like the global timeout, are deliberately not handled by viper as those are not something the project generally cares about except the CLI layer itself.
> [DEVX-980] Handle 'run' command flags with viper

- .github/workflows/test.yml
- internal/cmd/run/cypress.go
- internal/cmd/run/playwright.go
- internal/cmd/run/testcafe.go
Homogenize flags across the various `run` commands.
> Homogenize flags

- internal/appstore/appstore.go
- internal/cmd/ini/espresso.go
- internal/cmd/ini/xcuitest.go
- internal/msg/msg.go
Remove .sauceignore suggestion when uploading mobile apps.
When uploading non-mobile app:
```
16:47:15 INF Checking if /var/folders/jt/smmg8j4j4pgc2_8227dyqkm00000gp/T/saucectl-app-payload511038036/app.zip has already been uploaded previously
⠙ Uploading project /var/folders/jt/smmg8j4j4pgc2_8227dyqkm00000gp/T/saucectl-app-payload511038036/app.zip 
TIMEOUT: Failed to upload the project because it took too long. 
We *highly* recommend using .sauceignore file so that saucectl does not
create big archives with unnecessary files.
For more information, visit https://docs.saucelabs.com/testrunner-toolkit/configuration/bundling/index.html#exclude-files-from-the-bundle
or peruse some of our example repositories:
- https://github.com/saucelabs/saucectl-cypress-example
- …
```
> [DEVX-1071] Remove .sauceignore suggestion when uploading mobile apps

- internal/cmd/ini/cmd.go
- internal/cmd/ini/espresso.go
- internal/cmd/ini/xcuitest.go
- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/cloud.go
- internal/saucecloud/espresso.go
- internal/saucecloud/xcuitest.go
- internal/xcuitest/config.go
espresso: https://app.staging.saucelabs.net/tests/6fd584cfde1f4c2eaff45405d29a8036#1
xcuitest: https://app.staging.saucelabs.net/tests/9cf4d76aa85e48df99d092070b738c46#1
> [DEVX-1031] Add otherApps config for espresso and xcuitest

- internal/cmd/run/playwright.go
- internal/playwright/config.go
- internal/playwright/config_test.go
Add automatic sharding to playwright.
- [] Documentation Update (if none of the other choices apply)
> [DEVX-1076] Add automatic sharding to playwright

- internal/cypress/config.go
- internal/msg/msg.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/testcafe/config.go
Add missing defaults for rootDir.
Also fixes incomplete mode evaluation for playwright.
> Add missing defaults for rootDir

- internal/cmd/run/espresso.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
> [DEVX-1085] add useTestOrchestrator test option for espresso

- internal/cmd/run/puppeteer.go
- internal/puppeteer/config.go
Add args in config.yml
```
args:
- "--disable-features=site-per-process"
- "--start-fullscreen"
```
> [DEVX-1068] Add args for puppeteer runner

- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/cypress/config.go
- internal/docker/container.go
- internal/docker/cypress.go
- internal/docker/playwright.go
- internal/docker/puppeteer.go
- internal/docker/testcafe.go
- internal/espresso/config.go
- internal/flags/exporter.go
- internal/flags/exporter_test.go
- internal/job/starter.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/xcuitest.go
- internal/testcafe/config.go
- internal/xcuitest/config.go
Capture CLI flags, and attach them to the job as a `flags.json`.
Redact potentially sensitive values.
Example job: https://app.saucelabs.com/tests/63229550bfa649718204ff5340199523
> [DEVX-1106] capture cli flags

- internal/testcafe/config.go
Simulators were mislabled for testcafe.
> Fix simulator parsing for testcafe

- internal/resto/client.go
- internal/resto/client_test.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/xcuitest.go
- internal/tunnel/tunnel.go
Check owner of the tunnel while checking if tunnel is available.
If tunnel-parent is not provided, a tunnel can be falsely found to be available when it's not from VMs perspective.
> fix: Tunnel checks: Consider tunnel-parent

- internal/cypress/config.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/testcafe/config.go
Global env vars were applied & expanded on each suite. However, if env vars were defined on the suite directly, they were not expanded 🤕
> [DEVX-1128] Fix suite level envar expansion

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
Added additonal examples, restrictions and the missing global (root level) `env` attribute.
> Schema update

- Makefile
- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cypress/config.go
Add configuration field for reporters (Cypress only)
> [DEVX-956] Enable support for multiple reporters with cypress

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- api/v1alpha/generated/saucectl.schema.json
Restrict additional properties within defaults. This provides a bit more guidance as to what's allowed and where.
> Restrict additional properties within defaults

- .github/workflows/test.yml
- api/v1alpha/framework/espresso.schema.json
The use of `echo` prevented the propagation of the exit code and pipeline would not fail despite the generated schema not being up-to-date.
> Ensure schema check exits with correct code

- internal/cypress/config.go
- internal/cypress/config_test.go
- ensure cypress.json is not included in .sauceignore file
```
14:31:15 ERR failed to execute run command error="cypress.json is added into .sauceignore. In order to run your test successfully, please remove that from .sauceignore"
```
> [DEVX-1135] ensure cypress.json is included and under rootDir

- internal/appstore/appstore.go
- internal/appstore/appstore_test.go
query string: https://{host}/v1/storage/list?name=app.zip&per_page=100
Given 2000+ app.zip under my username.
Previous worst case: 45s+
Now worst case: 4s+
> [DEVX-1149] Update searching file cache query

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/testcafe.go
- internal/puppeteer/config.go
- internal/testcafe/config.go
- scripts/json-schema-bundler/package-lock.json
Set browserArgs as --start-fullscreen --start-in-incognito.
w/ args: https://app.saucelabs.com/tests/6608588934984d59aa18bed4272603a9
w/o args: https://app.saucelabs.com/tests/b46c5a06fc0e4d559503fb688e1c8a30
> [DEVX-1146] Support browserArgs for testcafe

- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/espresso.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
- internal/saucecloud/espresso_test.go
Add support `notAnnotation` for espresso.
> [DEVX-1170] Add notAnnotation flag

- internal/docker/docker.go
Also verified for other frameworks:
https://app.saucelabs.com/tests/74df134e8ee3487f8dfd66dcd9aacae9
https://app.saucelabs.com/tests/0741912bc0a142ecbfefaec39242b1f2
https://app.saucelabs.com/tests/051f1acc9b0449cf9166e87d071ace63
And `Env` works fine for sauce mode. Only didn't work for docker mode.
> [DEVX-1192] Fix docker env issue

- internal/appstore/appstore.go
- internal/cmd/ini/common.go
- internal/cmd/ini/common_test.go
- internal/espresso/config.go
- internal/espresso/config_test.go
Allow `*.aab` files to be defined for espresso apps.
> [DEVX-1186] Allow .aab assets for espresso runs

- internal/appstore/appstore.go
- internal/appstore/appstore_test.go
Improve searching cached file. Use sha256 to search files.
API: https://api.staging.saucelabs.net/v1/storage/files?sha256=e75db82d7036bccfe49645a5b637136575818ee75eb4fffdd08e10b027a1a0dc
```
17:41:45 INF Checking if /var/folders/7p/llkpr5bj14xf72c588j02xc40000gp/T/saucectl-app-payload2537679894/app.zip has already been uploaded previously
17:41:45 INF Skipping upload, using storage:303b7335-1477-4a57-ba6a-106b34ee5144
```
> [DEVX-1187] Search cached file by sha256

- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/puppeteer.go
- internal/puppeteer/config.go
Add `groups` for puppeteer config.
> [DEVX-1208] Support running group of test for puppeteer

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- api/v1alpha/generated/saucectl.schema.json
- api/v1alpha/subschema/common.schema.json
- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/cypress/config.go
- internal/espresso/config.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/saucecloud/cloud.go
- internal/testcafe/config.go
- internal/xcuitest/config.go
Print out system-out for mobile test.
```
saucectl run --show-console-log
...
+------------------------------------------------------+-------+------+------+-------+
| ESPRESSO TESTSUITE                                   | TESTS | PASS | FAIL | ERROR |
+------------------------------------------------------+-------+------+------+-------+
| com.example.android.testing.androidjunitrunnersample |    39 |   39 |    0 |     0 |
+------------------------------------------------------+-------+------+------+-------+
Name                              Duration    Status    Platform        Device
───────────────────────────────────────────────────────────────────────────────────────────────────────────
✔    saucy barista - test size            1m13s    passed    Android 11.0    Android GoogleApi …
```
> [DEVX-1213] Enable show-console-log for espresso/xcuitest

- internal/notification/slack/slack.go
> Remove duplicate build ID for slack message

- internal/job/starter.go
- internal/report/report.go
- internal/report/table/table.go
- internal/report/table/table_test.go
- internal/saucecloud/cloud.go
Add attempts count into report.
Given 3 retries.
rendered report:
```
Name                                Duration    Status    Browser      Platform      Attempts
──────────────────────────────────────────────────────────────────────────────────────────────────────
✔    Chrome using global mode setting         33s    passed    chrome 94    Windows 10           3
✖    setting2                                 47s    failed    chrome 94    Windows 10           4
──────────────────────────────────────────────────────────────────────────────────────────────────────
✖    1 of 2 suites have failed (50%)        3m12s
```
without retry:
```
Name                                Duration    Status    Browser      Platform      Attempts
───────────────────────────────────────────────────────────────── …
```
> [DEVX-1224] Add test attempts to report

- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/espresso.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
* Support the `notPackage` test option for espresso
> [DEVX-1241] add notPackage

- .github/workflows/release.yml
- .github/workflows/test.yml
- go.mod
> Update go to 1.17

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
- internal/playwright/config_test.go
> [DEVX-1247] Playwright test splitting

- go.mod
- go.sum
- internal/cmd/ini/initializer.go
- internal/cmd/run/run.go
- internal/logger/logger.go
- internal/rdc/client.go
- internal/rdc/client_test.go
- internal/resto/client.go
- internal/resto/client_test.go
- internal/saucecloud/cloud.go
When pulling job status from resto but with err, it will retry 3 times to fetch the status.  
logs as follows
16:26:39 ERR Failed to start suite. error="failed to retrieve job status for suite Chrome using global mode setting - examples/actions.spec.js. Reason: GET https://api.us-west-1.saucelabs.com/rest/v1.1/tianfeng92/jobs/1bc7190ca74b4c72b71083cbc251d22a giving up after 4 attempt(s): Get \"https://api.us-west-1.saucelabs.com/rest/v1.1/tianfeng92/jobs/1bc7190ca74b4c72b71083cbc251d22a\": dial tcp: lookup api.us-west-1.saucelabs.com: no such host" suite="Chrome using global mode setting - examples/actions.spec.js"
> [DEVX-1328] Add retry for polling job status from resto

- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/saucecloud/cloud.go
It will show the result table regarding to the framework
```
+-----------------------------+-------+------+------+-------+
| XCUITEST TESTSUITE          | TESTS | PASS | FAIL | ERROR |
+-----------------------------+-------+------+------+-------+
| com.saucelabs.mydemoapp.ios |     0 |    0 |    0 |     0 |
+-----------------------------+-------+------+------+-------+
```
```
+---------------------------------+-------+------+------+-------+
| ESPRESSO TESTSUITE              | TESTS | PASS | FAIL | ERROR |
+---------------------------------+-------+------+------+-------+
| com.saucelabs.mydemoapp.android |     7 |    7 |    0 |     0 |
+---------------------------------+-------+------+------+-------+
```
> [DEVX-1357] Fix espresso/xcuitest result table

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
e.g. https://app.saucelabs.com/tests/ab55c51283b4470dbf72f9fa9f1df4f1
> [DEVX-1067] Add playwright project support

- internal/cmd/run/cypress.go
- internal/cmd/run/cypress_test.go
Resolve env vars in Cypress Reporter configurations.
Fixes https://github.com/saucelabs/saucectl/issues/458
> [DEVX-1397] Expand env vars in cypress reporter config

- internal/appstore/appstore.go
Quality of life improvement for debugging.
> [DEVX-1408] Print payload checksum

- internal/apps/apps.go
- internal/appstore/appstore.go
- internal/cmd/configure/cmd.go
- internal/cmd/ini/cmd.go
- internal/cmd/ini/initializer.go
- internal/cmd/ini/initializer_test.go
- internal/cmd/run/run.go
- internal/config/config.go
- internal/cypress/config.go
- internal/cypress/native.go
- internal/docker/container.go
- internal/espresso/config.go
- internal/flags/device.go
- internal/flags/emulator.go
- internal/flags/quarantinemode.go
- internal/flags/simulator.go
- internal/framework/framework.go
- internal/msg/errormsg.go
- internal/msg/msg.go
- internal/playwright/config.go
- internal/puppeteer/config.go
- internal/rdc/client.go
- internal/resto/client.go
- internal/saucecloud/cloud.go
- internal/testcafe/config.go
- internal/testcomposer/testcomposer.go
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
Move error messages to `msg` package.
> [DEVX-545] move error msgs to a common package

- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/notification/slack/slack.go
- internal/usage/tracker.go
Reports to Segment slack configuration and sent/failed notifications count.
> [DEVX-1424] Send slack usage statistics

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
> [DEVX-1448] Add headless field for playwright

- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/testcafe.go
- internal/testcafe/config.go
e.g. https://app.saucelabs.com/tests/e3a65f79f7ce493fb3b0cef129495c74
https://app.saucelabs.com/tests/164376f17b324717824dc64ffa8bda06
> [DEVX-1449] Add headless for testcafe

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/cypress.go
- internal/cypress/config.go
Move `suite.config.headless` to `suite.headless`.
> [DEVX-1465] Move headless on suite level

- internal/cypress/config.go
- internal/cypress/native.go
To close https://github.com/saucelabs/saucectl/issues/484
> [DEVX-1525] Support bool for cypress FixturesFolder field

- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/testcafe.go
- internal/cypress/config.go
- internal/espresso/config.go
- internal/playwright/config.go
- internal/sentry/sentry.go
- internal/testcafe/config.go
- internal/usage/tracker.go
Capture the sharding usage.
Also includes a fix for the sentry upload status check.
> [DEVX-1512] Capture Sharding Usage

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
Updates schema to add macOS for Cypress / Playwright.
> [DEVX-1502] Add macOS to Schema

- cmd/saucectl/saucectl.go
- cmd/saucectl/saucectl_test.go
```
saucectl run --no-color
```
> [DEVX-1514] Add a flag to disable colorized output

- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/espresso.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
- internal/saucecloud/espresso_test.go
Add no constraints on TestOptions for Espresso jobs.
> [DEVX-1537] Use dynamic TestOptions parameters

- internal/config/config.go
Generate a build name in the case build is defined in the config but is set to an empty env var.
> Expand env vars in build name before setting a default

- internal/cypress/config.go
- internal/cypress/config_test.go
- internal/msg/msg.go
- internal/playwright/config.go
- internal/playwright/config_test.go
- internal/testcafe/config.go
- internal/testcafe/config_test.go
When sharding occurs and nothing matches, saucectl exits silently.
Introduce a new messaging + exiting with a failure code.
Output example:
> [DEVX-1556] Enhance in case of no match 

- internal/cypress/config.go
- internal/cypress/config_test.go
- internal/playwright/config.go
- internal/testcafe/config.go
- internal/testcafe/config_test.go
Sharding checks were badly implemented.
> fix: Sharding checks

- internal/cypress/config.go
- internal/cypress/config_test.go
Cypress patterns were not consistent between `saucectl` and Cypress behavior.
Some patterns passing with Cypress were skipping many files when saucectl proceeded the resolution.
> [DEVX-1557] Enhance matchings

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/cypress.go
- internal/cmd/run/playwright.go
- internal/concurrency/concurrency.go
- internal/concurrency/concurrency_test.go
- internal/cypress/config.go
- internal/cypress/config_test.go
- internal/fpath/file.go
- internal/playwright/config.go
- internal/testcafe/config.go
- internal/testcafe/config_test.go
Add an option to shard by concurrency.
> [DEVX-1555] Add sharding by concurrency

- internal/saucecloud/espresso.go
Enfor map copy for Espresso Tests that was resulting in always having the `shardIndex`  shared across the tests.
> [DEVX-1586] fix: Memory overwriting by forcing var copy

- internal/cmd/run/run.go
> [DEVX-1579] Add configurable appStoreTimeout

- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/config/config.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
- internal/saucecloud/xcuitest.go
- internal/xcuitest/config.go
> [DEVX-1528] Add audioCapture and networkCapture

- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
Display deprecation notice at the end and the beginning of the execution output.
```
$> saucectl run
10:15:28 WRN A new version of saucectl is available (v0.88.0)
10:15:28 INF Running Cypress in Sauce Labs
(.                          
#.                           
#.                           
.####################                    
#####////////*******/######                
.##///////*****************###/              
,###////*********************###              
####//***********************####             
###/************************###              
######********************###. ##           
(########################  ##     ##     
,######(#*         ##*   (##     
/############*          #####        
(########(  #########(    ### …
```
> [DEVX-1576] Display message at the beginning and  end of the execution

- .goreleaser.yml
> Remove sentry setting in .goreleaser.yml

- .github/workflows/test.yml
Apply temporary GIT permission workaround. Issue seems to affect container based jobs only. This will likely continue until the git version inside those containers has been updated. Till then, apply workaround.
See https://github.blog/2022-04-12-git-security-vulnerability-announced/.
> GIT Permission Workaround

- .github/workflows/test.yml
- internal/ci/ci.go
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
CI info would be collected by default. I added a flag to disable it `--no-auto-tagging`.
I added the info as much as possible. But for some CI provider, there are only few infos available. e.g. TeamCity.
A github action example: https://app.saucelabs.com/tests/d7986c2d93e144f1b4d238d74bda3940
> [DEVX-1630] Add CI info in jobs

- internal/cmd/run/cypress.go
> Fix cli driven params for cypress excludedTestFiles

- .github/workflows/test.yml
- .sauce/replay.yml
- api/v1alpha/framework/replay.schema.json
- api/v1alpha/generated/saucectl.schema.json
- api/v1alpha/global.schema.json
- internal/cmd/run/replay.go
- internal/cmd/run/run.go
- internal/fpath/file.go
- internal/puppeteer/replay/config.go
- internal/puppeteer/replay/config_test.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
- internal/saucecloud/replay.go
- internal/saucecloud/testcafe.go
- tests/e2e/replay/recording.json
Introduces puppeteer-replay.
PS: The UI does not yet support this framework. So don't bother clicking on any job links.
> [DEVX-1599] Puppeteer-Replay

- .sauce/espresso.yml
- .sauce/testcafe.yml
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- api/v1alpha/generated/saucectl.schema.json
- api/v1alpha/subschema/common.schema.json
- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/config/config.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/saucecloud/espresso.go
- internal/saucecloud/xcuitest.go
- internal/xcuitest/config.go
The config should be like
```
suites:
- name: "my test"
overwriteDeviceSettings:
audioCapture: true
instrumentation:
networkCapture: true
```
> [DEVX-1661] Update device settings for real device

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/replay.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
Allow windows 11 as a platform in the json schema.
> [DEVX-1671] Allow windows 11 in schema

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
- api/v1alpha/subschema/common.schema.json
Help users navigate supported framework versions by adding them to the JSON schema.
> [DEVX-1676] Document framework versions in JSON schema

- .github/workflows/release.yml
- .github/workflows/test.yml
Speed up pipelines by caching go modules.
> Cache go modules

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/replay.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
> [DEVX-1670] Document support for macOS 12

- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/apps/apps.go
- internal/saucecloud/cloud.go
Allow apps to be remote urls. Download to a temp directory before uploading to app storage.
> Download apps if urls are provided

- internal/docker/container.go
- internal/job/job.go
- internal/report/report.go
- internal/report/table/table.go
- internal/saucecloud/cloud.go
The result table will be like 
```
Suite 'saucy xcuitest' has reached 10.00s timeout
Results:
Name                                Duration    Status    Device                               Attempts
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖    saucy xcuitest                           10s    ?         iPhone_12_mini_IOS15_Beta_real_us           1
────────────────────────────────────────────────────────────────────────────────────────────────────────────────
✖    1 of 1 suites have failed (100%)         10s
Build Link: N/A
```
> [DEVX-1701] Log timeout status

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
Add `grep-invert` cli args to playwright runner. The args can be passed to the runner so no need to update playwright runner.
> [DEVX-1698] Add grep-invert for playwright runner

- internal/apps/apps.go
- internal/apps/apps_test.go
Fix issue when detecting remote app urls. `http` prefixed local filenames should not be considered remote urls.
> Parse the url instead of a simple regex

- internal/msg/errormsg.go
- internal/msg/msg.go
- internal/playwright/config_test.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
> Update outdated doc links in warning msgs

- .github/workflows/test.yml
- Makefile
- go.mod
- internal/apps/apps_test.go
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/replay.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/credentials/credentials.go
- internal/cypress/config.go
- internal/notification/slack/slack.go
- internal/report/json/json.go
- internal/resto/client_test.go
- internal/saucecloud/cloud.go
- internal/streams/in.go
- internal/streams/out.go
- internal/streams/stream.go
> [DEVX-1725] Cleanup

- internal/testcomposer/testcomposer.go
Propagate cloud runner version. Fixes cloud runner version retrieval when using `package.json` as a source.
> [DEVX-1735] Propagate cloud runner version

- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/replay.go
- internal/saucecloud/testcafe.go
`--runner-version` was ignored prior to this change, since the cloud determined runner version would always take precedence.
> Don't override pre-set runner versions

- internal/cmd/configure/cmd.go
- internal/cmd/configure/cmd_test.go
Masked output will be like
```
? SauceLabs username MY_USERNAME
? SauceLabs access key (*******-****-****-****-********1234)
```
> [DEVX-1741] Mask access key for saucectl configure

- internal/rdc/client.go
Add sanity check to troubleshoot https://github.com/saucelabs/saucectl/issues/553.
> Add sanity check for RDC job status retrieval

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
> [DEVX-1765] Add latest framework version in json schema

- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/generated/saucectl.schema.json
Reverts saucelabs/saucectl#557
> Revert "[DEVX-1765] Add latest framework version in json schema"

- internal/report/buildtable/buildtable.go
- internal/saucecloud/cloud.go
Test results that fail extremely early may not have a job url, thus no job id, thus doesn't belong to any builds. When querying for a build id, find and use a valid test result.
> Get build for first test result that has a valid job url

- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/generated/saucectl.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
Add `updateSnapshots` in playwright config.
first run https://app.saucelabs.com/tests/b2c995edb6aa4e2683af983dbeaec0bb
enable `updateSnapshot` https://app.saucelabs.com/tests/1152506b55b346c08f2186f233419178
disable `updateSnapshot` https://app.saucelabs.com/tests/f2c1b35b27b24bdf93d6491389990a6a
> [DEVX-1756] Add --update-snapshots for playwright

- install
Fixes #570 where there would be an error on linux/arm64
N/A
> add linux arm64 installation

- internal/cmd/run/run.go
Resolves #575 
This is a pretty simple addition. Just adds root-dir flag and binds it to the rootdir field
> added rootdir flag

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1/subschema/common.schema.json
- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/replay.schema.json
- api/v1alpha/framework/testcafe.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- api/v1alpha/subschema/common.schema.json
Avoid enhancing referenced objects with additional properties that are references. Those property references will not resolve correctly.
> Fix JSON Schema References

- api/saucectl.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- internal/espresso/config.go
- internal/espresso/config_test.go
- internal/saucecloud/espresso.go
- internal/saucecloud/xcuitest.go
- internal/saucecloud/xcuitest_test.go
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
> [DEVX-1807] Add testApp on suite level

- internal/cmd/run/run.go
Accommodate server queue by following more redirects. Redirects are not followed indefinitely to avoid accidental redirect loops (misconfigured proxies, the internet is an abyss).
I gave it a generous limit of 20 redirects, though I can reduce it to 15 if someone feels strongly about it?
> Prevent early job termination for queued jobs

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
Update framework versions in json schema.
> [DEVX-1821] Update framework versions in json schema

- api/saucectl.schema.json
- api/v1/subschema/sauce.schema.json
- api/v1alpha/subschema/sauce.schema.json
- internal/config/config.go
- internal/cypress/v1/config.go
- internal/cypress/v1alpha/config.go
- internal/espresso/config.go
- internal/job/starter.go
- internal/msg/errormsg.go
- internal/playwright/config.go
- internal/puppeteer/replay/config.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/replay.go
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
- internal/webdriver/webdriver.go
Add a `visibility` config option to control the default visibility of test results on Sauce.
This is only for sauce mode. I'm thinking we can add support for docker mode if requested. Open to including it in this PR though.
> Add visibility configuration for tests on sauce

- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/replay.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/cypress/suite/suite.go
- internal/espresso/config.go
- internal/playwright/config.go
- internal/puppeteer/replay/config.go
- internal/testcafe/config.go
- internal/usage/tracker.go
- internal/xcuitest/config.go
1. Add `LaunchOrder` in segment
2. Let `SortByHistory` return stable result. If the `history` is subset of `suites`, it should append rest of the suites in the default order.
> [DEVX-1813] Add launchOrder in segment

- .github/workflows/test.yml
- .sauce/cypress-10.yml
> Update cypress pipeline

- .github/workflows/release.yml
- .github/workflows/test.yml
- go.mod
- internal/apps/apps.go
- internal/saucecloud/xcuitest.go
> [DEVX-1856] Bump go to 1.19

- internal/cmd/ini/cmd.go
- internal/cmd/ini/common.go
- internal/cmd/ini/common_test.go
- internal/cmd/ini/initializer.go
Fix saucectl init validation for cypress 10+. The suffix should be `cjs, js, ts, mjs`
> [DEVX-1862] Fix saucectl init validation for cypress 10

- api/global.schema.json
- api/saucectl.schema.json
Previous PR added apitest to saucectl schema, but forgot to add it to the top level `kind` enum.
> add apitest to top level kind enum

- internal/cmd/configure/cmd.go
Make subsequent runs of `saucectl configure` explicit that creds are already set and ask to overwrite. The survey library we're using for the interactive set credentials experience doesn't allow to mask a default value. Currently, we mask the default accessKey, but are forced to save the masked key to credentials.yml.
Instead, show the current creds, if already set (accessKey of course masked), and ask if they want to overwrite, at which point the existing interactive prompt starts.
**New creds**
**Overwrite**
> Ask to overwrite creds if they already exist

- internal/espresso/config.go
- internal/xcuitest/config.go
Fix typo in struct tag in espresso/xcuitest config.
> [DEVX-1920] Fix typo in espresso/xcuitest config

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/puppeteer.schema.json
- api/v1alpha/framework/testcafe.schema.json
> schema updates

- internal/cmd/configure/cmd.go
- internal/cmd/ini/cmd.go
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/replay.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
Using async way to send data to segment.
> [DEVX-1919] Send data to segment in async way

- internal/sauceignore/matcher.go
- internal/sauceignore/matcher_test.go
Make sure `sauce-runner.json` is always included
> [DEVX-1866] Make sure sauce-runner.json is included

- internal/appstore/appstore.go
- internal/cmd/storage/upload.go
- internal/mocks/storage.go
- internal/saucecloud/cloud.go
- internal/storage/storage.go
Optimize storage queries by avoiding pagination when it isn't necessary.
> Optimize storage queries

- .github/workflows/test.yml
- .sauce/cypress-10.yml
- api/saucectl.schema.json
- api/v1alpha/subschema/sauce.schema.json
- internal/region/region.go
Add `us-east-4` as a selectable region.
> Add us-east-4

- internal/saucecloud/cloud.go
- internal/sauceignore/matcher.go
- internal/sauceignore/matcher_test.go
Upload the project/runner config as a separate payload. Since the config file can have dynamic values (e.g. build names pulled from environment variables), it can cause cache misses when uploading the test payload. So upload the config separately to increase chances of cache hits in app storage.
> Upload runner config in separate payload

- internal/cmd/run/cypress.go
- internal/cmd/run/playwright.go
- internal/cmd/run/puppeteer.go
- internal/cmd/run/replay.go
- internal/cmd/run/testcafe.go
- internal/espresso/config.go
- internal/msg/errormsg.go
- internal/saucecloud/cloud.go
- internal/xcuitest/config.go
`us-east-4` is not a feature complete cluster. Provide the user feedback about this as soon as possible.
> Add regional restrictions

- .github/workflows/test.yml
- api/global.schema.json
- api/saucectl.schema.json
- api/v1alpha/framework/playwright-cucumberjs.schema.json
- internal/cmd/run/cucumber.go
- internal/cmd/run/playwright.go
- internal/cmd/run/run.go
- internal/cucumber/config.go
- internal/docker/cucumber.go
- internal/docker/docker.go
- internal/saucecloud/cucumber.go
- tests/e2e/playwright-cucumberjs/.sauce/config.yml
- tests/e2e/playwright-cucumberjs/features/greeting.feature
- tests/e2e/playwright-cucumberjs/features/support/steps.js
- tests/e2e/playwright-cucumberjs/package-lock.json
- tests/e2e/playwright-cucumberjs/package.json
Job example: https://app.saucelabs.com/tests/5715ca51c1ce4e4ca7a4f9fc8331e09d
> [DEVX-1890] Add cucumber config

- internal/appstore/appstore.go
- internal/storage/storage.go
Return more readable err msg for storage 429 code.
> [DEVX-1943] Return user-friendly err msg for storage 429 resp

- .sauce/playwright.yml
- internal/webdriver/webdriver.go
- tests/e2e/playwright/example.test.js
Set framerate to 25fps for videos recorded for tests run on sauce.
> Add prop to set fps

- api/saucectl.schema.json
- api/v1alpha/framework/playwright.schema.json
- internal/playwright/config.go
- internal/playwright/config_test.go
- internal/webdriver/webdriver.go
Mac: https://app.staging.saucelabs.net/tests/c175412d8b944a0e8210a90133e4d5fc
Windows: https://app.staging.saucelabs.net/tests/108cd81b3a0d4b77af20a3ab13189777
> [DEVX-1973] Support playwright + chrome

- api/saucectl.schema.json
- api/v1alpha/framework/playwright.schema.json
- internal/cmd/run/playwright.go
- internal/playwright/config.go
job: https://app.saucelabs.com/tests/200aaee28cbc4c499cb11357086f8149
> [DEVX-1979] Add workers settings for playwright

- .github/workflows/release.yml
- .github/workflows/test.yml
- tests/e2e/playwright-cucumberjs/.sauce/config.yml
- tests/e2e/playwright-cucumberjs/features/greeting.feature
- tests/e2e/playwright-cucumberjs/features/support/steps.js
> [DEVX-1996] Pipeline Maintenance

- .github/workflows/release.yml
It should skip brew release for pre-release job. Verified in this job https://github.com/saucelabs/saucectl/actions/runs/3423399168
> [DEVX-2011] Skip brew release for pre-release job

- .github/workflows/release.yml
Fix release pipeline.
pre-release:  https://github.com/saucelabs/saucectl/actions/runs/3465895902/jobs/5789153825
release: https://github.com/saucelabs/saucectl/actions/runs/3466641149/jobs/5790705130
> Fix publishing node-saucectl

- internal/node/package.go
Exclude `@playwright/test` from dependencies as it's already provided by sauce. Verified on playwright and cucumber test both.
```
12:00:40 INF Skipping dependency @playwright/test, as it's provided by Sauce Labs
```
> [DEVX-2008] Exclude @playwright/test from dependencies

- internal/apitest/runner.go
- internal/cmd/run/apitest.go
Add missing `select-suite` support in apitest.
> Add select-suite filter from apitest

- internal/cypress/v1/config.go
- internal/cypress/v1alpha/config.go
- internal/msg/errormsg.go
- internal/playwright/config.go
- internal/puppeteer/replay/config.go
- internal/testcafe/config.go
- Enhance validation of config file
- Warn when platform is using default
- Uniformize checks
> [DEVX-2053] Validate config file

- internal/segment/segment.go
Allow data to be funnelled to Pendo as well.
> Add pendo integration

- cmd/saucectl/saucectl.go
- internal/artifacts/artifacts.go
- internal/cmd/artifacts/cmd.go
- internal/cmd/artifacts/download.go
- internal/cmd/artifacts/list.go
- internal/cmd/artifacts/upload.go
- internal/mocks/artifacts.go
- internal/saucecloud/artifactservice.go
Interact with job's artifacts.
List
```
saucectl artifacts list <job_id>
```
Download
```
saucectl artifacts download <job_id> "*.log"
```
Upload
```
saucectl artifacts upload <job_id> "test2.log"
```
It can also generate json format to console.
> [DEVX-1827] Add saucectl artifacts cmd

- api/saucectl.schema.json
- api/v1alpha/framework/testcafe.schema.json
When specifying `iOS` platformName in simulator configuration, there is a warning because this is not considered as a valid value.
It appears that the mapping is incorrect. Currently only supported platform for simulators on TestCafe is `iOS`.
Unexpected output:
```
Running version 0.120.0
There is 5 validation errors found in .sauce/config.yml:
- value must be one of "macOS 11.00", "macOS 12", "Windows 10", "Windows 11" in /suites/0/simulators/0/platformName
- value must be one of "macOS 11.00", "macOS 12", "Windows 10", "Windows 11" in /suites/1/simulators/0/platformName
- value must be one of "macOS 11.00", "macOS 12", "Windows 10", "Windows 11" in /suites/2/simulators/0/platformName
- value must be one of "macOS 11.00", "macOS 12", "Windows 10", "Windows 11" in …
```
> Update TestCafe Platform

- internal/saucecloud/testcafe.go
The root cause for non-workable timeout is missing job config. Unified the common part of the job config.
> [DEVX-2096] Fix missing config for testcafe

- internal/insights/testrun.go
To avoid spamming the console with warning, do not try to convert an empty string to float.
> XML Parsing: Avoid warning on empty values

- internal/insights/testrun.go
Remove `omitempty` as `duration` is a needed value even if it's a zero value
> Remove omitempty

- internal/framework/framework.go
- internal/msg/msg.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
- internal/testcomposer/testcomposer.go
- internal/testcomposer/testcomposer_test.go
Add really visible depreciation and flagger for removal warning.
Deprecation message example:
Removal message example:
> Enhance depreciation warnings

- internal/saucecloud/imagerunner.go
Adjust the timeouts based on internal feedback. These are still arbitrary values and will likely need to be fine tuned some more in the future.
> Adjust image runner timeouts

- internal/config/config.go
- internal/config/config_test.go
- internal/docker/container.go
- internal/saucecloud/cloud.go
- internal/saucecloud/imagerunner.go
Clean up the artifact download logic by moving Job and runner specific conditionals to their respective packages.
> Clean up artifact download logic

- .github/workflows/docker-release.yml
Fix empty container tag that resulted in broken smoke test.
> Set our own docker image version

- internal/insights/testrun.go
> Stop generating UUID for test-runs api

- internal/cmd/artifacts/cmd.go
- internal/cmd/ini/initializer.go
- internal/cmd/run/run.go
- internal/http/errors.go
- internal/http/testcomposer.go
- internal/http/testcomposer_test.go
- internal/saucecloud/artifactservice.go
Same change as https://github.com/saucelabs/saucectl/pull/683, but for testcomposer.
> Refactor testcomposer

- .github/workflows/docker-release.yml
Job: https://github.com/saucelabs/saucectl/actions/runs/4168932202/jobs/7216306010
> Fix docker release smoke test

- internal/cmd/jobs/cmd.go
- internal/cmd/run/run.go
- internal/http/userservice.go
- internal/iam/userservice.go
- internal/saucecloud/cloud.go
- internal/saucecloud/jobservice.go
Same as https://github.com/saucelabs/saucectl/pull/683, but for iam.
> Refactor iam

- internal/apps/apps.go
- internal/cmd/run/run.go
- internal/cmd/storage/cmd.go
- internal/http/appstore.go
- internal/http/appstore_test.go
- internal/saucecloud/cloud.go
- internal/storage/storage.go
Same as https://github.com/saucelabs/saucectl/pull/683, but for the app store.
> Refactor AppStore

- .sauce/apitest.yml
- api/saucectl.schema.json
- api/v1alpha/framework/apitest.schema.json
- internal/apitest/config.go
- internal/apitest/runner.go
- internal/msg/errormsg.go
- tests/api/Flow Control/input.yaml
- tests/api/Flow Control/unit.yaml
HookID is not intented to be supported as we want to hide it from the config. 
As API Testing is not out, we can safely remove hookID support, that will cause a small breaking change on that scope only.
HookID is now mentioned only when one is missing to trigger a test.
> API Testing: Update wording / Remove hookID support

- internal/cmd/artifacts/cmd.go
- internal/cmd/ini/initializer.go
- internal/cmd/run/run.go
- internal/http/errors.go
- internal/http/resto.go
- internal/http/resto_test.go
- internal/saucecloud/artifactservice.go
Same as https://github.com/saucelabs/saucectl/pull/683, but for resto.
> Refactor resto

- internal/apitest/runner.go
- internal/msg/errormsg.go
A project is attached to a region. It adds clarity to mention that the project has not been found in the defined region, as some users already faced that issue (Project available in `us-west-1` but config targeting `eu-central-1`)
> Clarify that a project is tied to a region

- internal/cmd/run/imagerunner.go
Add usage tracking for imagerunner as well.
> Add usage tracking to imagerunner

- .github/workflows/test.yml
- .sauce/imagerunner.yml
- tests/e2e/imagerunner/hello.txt
Add an e2e test of imagerunner to the pipeline.
> Add imagerunner test to the pipeline

- .sauce/cypress-10.yml
- .sauce/testcafe.yml
Bump framework version to test against the newest versions.
> Bump framework versions

- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- go.mod
> Bump go to 1.20

- .sauce/cypress-10.yml
- .sauce/cypress.yml
- .sauce/playwright.yml
- .sauce/testcafe.yml
Update framework version in the examples.
> Update Framework version

- internal/http/webdriver.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/cypress_test.go
- internal/saucecloud/playwright.go
- internal/saucecloud/replay.go
- internal/saucecloud/testcafe.go
Avoid concatenating with `,` the multiple values and pass parameters through `otherApps`.
> Specify packages through otherApps field

- .github/workflows/test.yml
- .golangci.yml
- internal/archive/zip/zip.go
- internal/cmd/ini/common.go
- internal/docker/docker.go
`golangci-lint@1.52.0` introduced new errors.
This PR manages them.
> fix: Correct linting errors reported by golangci-lint@1.52.0

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/cypress.schema.json
- api/v1alpha/framework/playwright-cucumberjs.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/replay.schema.json
- api/v1alpha/framework/testcafe.schema.json
> Enable macOS 13

- internal/cmd/run/cucumber.go
> Add select-suite for cucumber

- .sauce/apitest.yml
- internal/apitest/runner.go
- internal/apitest/runner_test.go
When running locally defined tests, load input and unit files with either yml/yaml extensions.
* Added a warning if a dir matches the given `testMatch` but is missing the required files.
* Added a warning if no dirs match the given `testMatch`. Though I think technically this should fail the run?
> Load either yml,yaml files for local tests

- .github/workflows/test.yml
- internal/saucecloud/cloud.go
See test details here: https://github.com/saucelabs/saucectl/actions/runs/4672213976/jobs/8274197802?pr=742
> Fix async mode

- internal/http/imagerunner.go
> Add err handling for imagerunner artifacts download

- internal/cmd/ini/initializer.go
- internal/cmd/ini/initializer_test.go
- internal/framework/framework.go
- internal/framework/search_test.go
- internal/http/testcomposer.go
- internal/http/testcomposer_test.go
- internal/mocks/frameworks.go
Use Frameworks v2 API.
Simplify the `frameworks.Frameworks()` signature.
> Use frameworks V2 API

- internal/saucecloud/retry/junitretrier.go
- internal/saucecloud/retry/junitretrier_test.go
Set `TestToRun` in case of running `XCUITest`.
> fix: smartRetry for XCUITest

- internal/cmd/ini/cmd.go
- internal/cmd/ini/common.go
- internal/cmd/ini/common_test.go
- internal/cmd/ini/cypress.go
- internal/cmd/ini/initializer.go
- internal/cmd/ini/initializer_test.go
- internal/cmd/ini/playwright.go
- internal/cmd/ini/testcafe.go
Remove docker support in `init` command.
> Remove support for Docker in init

- api/saucectl.schema.json
- api/v1alpha/subschema/sauce.schema.json
Add `launchOrder` for `v1alpha` schema.
> Add launchOrder for v1alpha in Schema

- internal/imagerunner/imagerunner.go
- internal/saucecloud/imagerunner.go
> Add tunnel for image runner

- internal/cmd/run/imagerunner.go
- internal/imagerunner/imagerunner.go
- internal/saucecloud/imagerunner.go
```
$ saucectl-local run 
13:30:28 WRN A new version of saucectl is available (v0.140.0)
13:30:28 INF Performing tunnel readiness check... timeout=30s
13:30:58 ERR failed to execute run command error="tunnel not found"
```
> Check tunnel availability for image runner

- api/saucectl.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- internal/cmd/run/xcuitest.go
- internal/concurrency/concurrency.go
- internal/concurrency/concurrency_test.go
- internal/cucumber/config.go
- internal/cypress/v1/config.go
- internal/cypress/v1alpha/config.go
- internal/playwright/config.go
- internal/testcafe/config.go
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
Introducing `shardConfig` field to suite. The shardConfig will contain a list of tests and tests are splited by `\n`
> Add sharding for XCUITest

- internal/xcuitest/config.go
> Fix XCUITest sharding suite name

- api/saucectl.schema.json
- api/v1alpha/framework/imagerunner.schema.json
- internal/imagerunner/config.go
- internal/imagerunner/config_test.go
- internal/imagerunner/imagerunner.go
- internal/msg/errormsg.go
- internal/saucecloud/imagerunner.go
> Add resourceProfile for HTO

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1/subschema/common.schema.json
- api/v1alpha/framework/playwright-cucumberjs.schema.json
> Add missing smartRetry in JSON schema

- internal/apitest/errors.go
- internal/apitest/runner.go
- internal/apitest/runner_test.go
- internal/http/apitester.go
Refactor the APIT area responsible for collecting test results. Prior to this change, errors returned by the platform were swallowed.
Some other minor improvements were made along the way to improve code hygiene.
> Refactor APIT Test Result Collection

- internal/espresso/config.go
- internal/junit/junit.go
- internal/msg/errormsg.go
- internal/saucecloud/retry/junitretrier.go
- internal/saucecloud/retry/junitretrier_test.go
Support smart retry for XCUITest test.
> Improve smart retry for mobile

- internal/apitest/config.go
- internal/apitest/runner.go
Add support for `--dry-run` when running APITesting tasks.
> Add dry-run support for APITesting

- internal/msg/errormsg.go
> fix: Refine error msg for smart retry

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
> Bump available framework version

- internal/cmd/configure/cmd.go
- internal/cmd/configure/list.go
- internal/credentials/credentials.go
- internal/credentials/credentials_test.go
- internal/iam/auth.go
> feat: Add saucectl configure list

- api/saucectl.schema.json
- api/v1alpha/framework/playwright.schema.json
- internal/cmd/run/playwright.go
- internal/cypress/v1/config.go
- internal/cypress/v1alpha/config.go
- internal/msg/errormsg.go
- internal/playwright/code/parser.go
- internal/playwright/code/parser_test.go
- internal/playwright/config.go
- internal/playwright/grep/grep.go
- internal/playwright/grep/grep_test.go
Add supports for `shardGrepEnabled` for playwright projects.
> Add support for shardGrepEnabled for playwright

- internal/http/webdriver.go
Removes now useless flag `devX`.
> Remove useless flag devX

- internal/imagerunner/config.go
`--env` was not supported for ImageRunner
`defaults.env` was not supporter for ImageRunner
> Add support for Env / Defaults.Env for ImageRunner

- api/saucectl.schema.json
- api/v1alpha/framework/espresso.schema.json
Include additional test options that were documented in https://github.com/saucelabs/sauce-docs/pull/2147 to the schema.
> docs: Describe additional test options for espresso

- api/saucectl.schema.json
- api/v1alpha/framework/imagerunner.schema.json
- internal/imagerunner/config.go
- internal/imagerunner/config_test.go
- internal/msg/errormsg.go
Check against Regex not fixed list.
> Enhance check for resource profile

- internal/http/rdcservice.go
- internal/http/resto.go
- internal/report/json/json.go
- internal/report/report.go
- internal/saucecloud/cloud.go
This PR is to refine following issues
* make it more readable
* fix JSON report inaccurate fields(missing artifacts, uncompleted filePath, unnecessary passThreshold)
Before
```
[
{
"name": "Firefox Win",
"duration": 33032374708,
"startTime": "2023-07-24T13:04:18.320734-07:00",
"endTime": "2023-07-24T13:05:17.02408-07:00",
"status": "failed",
"browser": "firefox 113",
"platform": "Windows 11",
"deviceName": "",
"url": "https://app.saucelabs.com/tests/9d561334be0f4af1ac10dbc6e4ed6246",
"artifacts": null,
"origin": "sauce",
"attempts": 2,
"passThreshold": false
}
]
```
After
VDC
```
[
{
"name": "Firefox Win",
"duration": 38252464375,
"startTime": "2023-07-24T17:22:30.111891-07:00",
"endTime": "2023-07-24T17:23:43.005487-07:00",
"status": "failed",
"browser": "firefox 113",
"platform": …
```
> chore: Refine generating JSON&JUint report

- tests/e2e/playwright-cucumberjs/package-lock.json
- tests/e2e/playwright-cucumberjs/package.json
Bump deps to address https://github.com/saucelabs/saucectl/security/dependabot/40
> chore: Bump e2e dependencies

- .sauce/cypress-10.yml
- .sauce/cypress.yml
- .sauce/espresso-env-var.yml
- .sauce/espresso.yml
- .sauce/playwright.yml
- .sauce/testcafe.yml
- internal/junit/junit.go
- internal/junit/junit_test.go
- internal/report/junit/junit.go
- internal/report/junit/junit_test.go
The "last refactor" that consolidates all of the generic junit functionality under the junit package.
Also: Removed slack notifications from our pipelines, since they don't seem to be working any longer anyway and this feature is no longer in active maintenance.
> chore: junit consolidation

- .sauce/cypress-10.yml
- .sauce/playwright.yml
- .sauce/testcafe.yml
- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
Cypress framework version 12.17.4, runner version 10.5.0.
Playwright framework version 1.37.1, runner version 2.21.0 .
TestCafe framework version 3.2.0, runner version 3.1.0.
> feat: Add latest frameworks version

- internal/http/rdcservice.go
- internal/job/starter.go
The fixed request body is
```
{
...
"settings_overwrite": {
"audio_capture": true,
"instrumentation": {
"network_capture": true
}
},
"kind": "ios"
}
```
> fix: Incorrect serialization of RDC appSettings caused them to never take effect

- .github/workflows/codeql.yml
- .github/workflows/docker-release.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- go.mod
> chore: Use go 1.21

- internal/cucumber/config.go
- internal/cypress/suite/suite.go
- internal/cypress/v1/config.go
- internal/cypress/v1alpha/config.go
Leftover field that was used to switch between docker and sauce mode.
> refactor: remove obsolete mode field

- internal/imagerunner/utils.go
- internal/imagerunner/utils_test.go
> fix: canonicalize service name correctly

- internal/http/webdriver.go
Terminate idle connections before the server does.
> fix: terminate idle connections

- api/saucectl.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- internal/xcuitest/config.go
- internal/xcuitest/config_test.go
Support `statusBarOverrideTime` for XCUITest on Simulator test. This field will update the time on status bar.
> feat: Support statusBarOverrideTime for XCUITest Sim

- internal/cmd/run/apitest.go
- internal/cmd/run/cucumber.go
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/imagerunner.go
- internal/cmd/run/playwright.go
- internal/cmd/run/replay.go
- internal/cmd/run/run.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
Instead of partially instantiating all the service clients, fully instantiate them when they are needed.
> chore: Improve client instantiation

- internal/cmd/ini/cmd.go
- internal/cmd/ini/initializer.go
- internal/cmd/ini/initializer_test.go
- internal/cmd/ini/playwright.go
Fixes the incomplete playwright init workflow. It now properly generates a fully saucectl spec legal yaml file.
> fix: incomplete playwright init

- .sauce/testcafe.yml
> chore: enable testcafe iOS tests

- internal/apitest/runner.go
- internal/saucecloud/cloud.go
- internal/saucecloud/imagerunner.go
- internal/tunnel/tunnel.go
Improve tunnel related log lines
> chore: Enhance Logging for Tunnel-Related Processes

- internal/cmd/imagerunner/cmd.go
- internal/cmd/imagerunner/stop.go
Add cli to stop a SO container.
```
$ saucectl imagerunner stop b013c3a0ab0c466fbc0149209b67140d
Stopping container b013c3a0ab0c466fbc0149209b67140d...
```
> feat: Add saucectl imagerunner stop cli

- internal/cmd/docker/push.go
- internal/http/imagerunner.go
Update API for getting docker auth.
> chore: Update API for getting docker auth

- api/saucectl.schema.json
- api/v1/subschema/artifacts.schema.json
- api/v1alpha/framework/imagerunner.schema.json
- api/v1alpha/subschema/artifacts.schema.json
- internal/config/config.go
- internal/cucumber/config.go
- internal/cypress/v1/config.go
- internal/playwright/config.go
- internal/testcafe/config.go
> feat: Support archive folders

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
[DEVX-2899]
[DEVX-2899]: https://saucedev.atlassian.net/browse/DEVX-2899?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore(schema): add latest versions

- .sauce/cypress-10.yml
- .sauce/playwright.yml
- .sauce/testcafe.yml
- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
Add
- Cypress 13.12.0(runner v12.5.0)
- Playwright 1.45.0(runner v2.30.0)
- TestCafe 3.6.1(runner v3.7.0)
Remove
- Cypress 12.14.0
- Playwright 1.35.1
- TestCafe 2.6.2
> chore: Monthly framework update

- .github/workflows/release.yml
- .github/workflows/test.yml
- .goreleaser.yml
> build: Use GoReleaser v2

- api/saucectl.schema.json
- api/v1alpha/framework/testcafe.schema.json
- internal/cmd/run/testcafe.go
- internal/testcafe/config.go
> feat: Support TestCafe esm flag

- api/saucectl.schema.json
- api/v1alpha/framework/playwright-cucumberjs.schema.json
- internal/cucumber/config.go
- internal/cucumber/scenario/scenario.go
- internal/cucumber/tag/matcher.go
Note: Scenarios with the same name are grouped together to create a job.
Test Example: https://app.saucelabs.com/builds/vdc/10a0f2e2f67835589a3107d5e88f4030
> feat: Support shard by scenario

- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
> refactor: Extract framework validation

- internal/msg/msg.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
Extract framework EOL and removal notice so it can be reused for runtime.
> refactor: Extract framework EOL and removal notice

- .github/workflows/codeql.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- Dockerfile
- go.mod
> build: Use go 1.23

- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/playwright.go
- internal/saucecloud/testcafe.go
Fix `--runner-version` flag setting.
> fix: respect --runner-version flag

- api/saucectl.schema.json
- api/v1alpha/subschema/npm.schema.json
Add `usePackageLock` for v1alpha schema. Missed it in the PR that introduced the feature.
> fix: add usePackageLock for v1alpha schema

- internal/cmd/storage/upload.go
- internal/http/apitester.go
- internal/http/appstore.go
- internal/http/appstore_test.go
- internal/multipartext/multipart.go
- internal/saucecloud/cloud.go
- internal/saucecloud/espresso.go
- internal/saucecloud/retry/saucereportretrier.go
- internal/saucecloud/retry/saucereportretrier_test.go
- internal/saucecloud/xcuitest.go
- internal/storage/storage.go
Group filename, description and incoming tags into a struct.
> refactor: Organize file details for uploading archives

- internal/usage/tracker.go
Track usage of the newly introduced package lock feature.
> fix: track package lock usage

- .github/workflows/test.yml
- .golangci.yml
- .sauce/cypress-10.yml
- .sauce/testcafe.yml
- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/testcafe.schema.json
- internal/cmd/docker/push.go
- internal/http/resto_test.go
- internal/multipartext/seeker.go
> chore: Bump Cypress & TestCafe version

- api/saucectl.schema.json
- api/v1alpha/framework/playwright-cucumberjs.schema.json
Fix JSON schema. Docs are correct.
> fix: Cucumber formatOptions should be an object

- internal/saucecloud/cloud.go
In `--async` mode, errors starting a job were suppressed. Instead, when logging a suite's results, always log the error, if present.
[DEVX-3074]
[DEVX-3074]: https://saucedev.atlassian.net/browse/DEVX-3074?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Make sure job errors are always printed

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
[DEVX-3114]
[DEVX-3114]: https://saucedev.atlassian.net/browse/DEVX-3114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Add latest frameworks to schema

- internal/cmd/jobs/get.go
- internal/cmd/jobs/list.go
- internal/cmd/run/cucumber.go
- internal/cmd/run/cypress.go
- internal/cmd/run/espresso.go
- internal/cmd/run/playwright.go
- internal/cmd/run/replay.go
- internal/cmd/run/testcafe.go
- internal/cmd/run/xcuitest.go
- internal/http/rdcservice_test.go
- internal/http/webdriver_test.go
- internal/saucecloud/cloud.go
- internal/saucecloud/cloud_test.go
- internal/saucecloud/cucumber.go
- internal/saucecloud/cypress.go
- internal/saucecloud/espresso.go
- internal/saucecloud/playwright.go
- internal/saucecloud/replay.go
- internal/saucecloud/retry/basicretrier.go
- internal/saucecloud/retry/basicretrier_test.go
- internal/saucecloud/retry/junitretrier.go
- internal/saucecloud/retry/junitretrier_test.go
- internal/saucecloud/retry/retrier.go
- internal/saucecloud/retry/saucereportretrier.go
- internal/saucecloud/retry/saucereportretrier_test.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/xcuitest.go
Propagate the recently introduced global context across code that handles project uploads and job commands. This makes those interactions finally cancellable.
> feat: cancellable project uploads and job commands

- internal/saucecloud/imagerunner.go
Remove the now redundant implementation of context cancellation inside ImageRunner by using the global context provided by the CLI entry point. There are no business logic changes here.
> refactor: imagerunner global context

- api/saucectl.schema.json
- api/v1alpha/framework/espresso.schema.json
- api/v1alpha/framework/xcuitest.schema.json
- internal/cmd/run/espresso.go
- internal/cmd/run/xcuitest.go
- internal/saucecloud/espresso.go
- internal/saucecloud/xcuitest.go
Updated description of each instrumentation capabilities, aligning the description with the [sauce-doc](https://github.com/saucelabs/sauce-docs):
[Configuring Your Espresso Tests | Sauce Labs Documentation](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/espresso/#networkcapture) 
[Configuring Your XCUITest Tests for Real Devices and Simulators | Sauce Labs Documentation](https://docs.saucelabs.com/mobile-apps/automated-testing/espresso-xcuitest/xcuitest/#networkcapture)
> fix: updated description of instrumentation capabilities

- internal/saucecloud/cloud.go
[DEVX-3156]
[DEVX-3156]: https://saucedev.atlassian.net/browse/DEVX-3156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Don't skip log printing if job has an id and has completed

- api/saucectl.schema.json
- api/v1/framework/cypress.schema.json
- api/v1alpha/framework/playwright.schema.json
- api/v1alpha/framework/testcafe.schema.json
[INT-75]
[INT-75]: https://saucedev.atlassian.net/browse/INT-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> chore: Add latest framework versions to json schema

- internal/saucecloud/cloud.go
Clarify some ambiguous warn level messages by making them debug level and if applicable better summarize the actual effect of the failure.
[INT-68]
[INT-68]: https://saucedev.atlassian.net/browse/INT-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Clarify extraneous logging

- internal/cmd/run/playwright.go
- internal/saucecloud/playwright.go
- internal/saucecloud/playwright_test.go
Pass project as a pointer to ensure node path in valid
> [INT-139] pass project as a pointer

- internal/cmd/run/cypress.go
- internal/cmd/run/testcafe.go
- internal/saucecloud/cypress.go
- internal/saucecloud/testcafe.go
- internal/saucecloud/testcafe_test.go
Pass project as a pointer to ensure node path in valid in cypress and testcafe
> [INT-167]  pass project as a pointer in cypress and testcafe 

- api/saucectl.schema.json
- api/v1alpha/framework/playwright.schema.json
Fix invalid version for Playwright.
> [INT-186] Playwright version 1.52.2 => 1.52.0

- .sauce/testcafe.yml
- api/saucectl.schema.json
- api/v1alpha/framework/testcafe.schema.json
- internal/saucecloud/testcafe.go
- internal/testcafe/config.go
This PR adds requesting ARM capabilities for TestCafe.
> [INT-367] add testcafe ARM support

- internal/http/rdcservice.go
- internal/http/rdcservice_test.go
> Consider "StatusComplete" also as passed
